-- Internal storage used only by authenticated server routes with the service role.
-- No browser client receives the service key, and anon/authenticated access is revoked.

create table if not exists public.dashboard_clients (
  id uuid primary key default gen_random_uuid(),
  business_email text not null unique,
  business_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.dashboard_clients (id, business_email, business_name)
values ('00000000-0000-4000-8000-000000000001', 'tiressosrescue@gmail.com', 'Tires SOS Rescue')
on conflict (id) do update set
  business_email = excluded.business_email,
  business_name = excluded.business_name,
  updated_at = now();

create table if not exists public.ad_connections (
  id integer primary key,
  connections jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.daily_metrics (
  id bigint generated by default as identity primary key,
  client_id uuid not null references public.dashboard_clients(id) on delete cascade,
  platform text not null check (platform in ('google_ads', 'meta_ads', 'yelp')),
  metric_date date not null,
  spend numeric(12,2) not null default 0,
  clicks numeric(12,2) not null default 0,
  conversions numeric(12,2) not null default 0,
  conversion_value numeric(12,2) not null default 0,
  impressions numeric(14,2) not null default 0,
  click_through_rate numeric(8,4) not null default 0,
  cost_per_click numeric(12,4) not null default 0,
  roas numeric(12,4) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (client_id, platform, metric_date)
);

create table if not exists public.optimization_runs (
  id bigint generated by default as identity primary key,
  client_id uuid not null references public.dashboard_clients(id) on delete cascade,
  run_date timestamptz not null,
  run_type text not null default 'daily_recommendation',
  budget_allocation jsonb not null default '{}'::jsonb,
  metrics jsonb not null default '{}'::jsonb,
  recommendations jsonb,
  actions_taken jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.ad_variations (
  id bigint generated by default as identity primary key,
  client_id uuid not null references public.dashboard_clients(id) on delete cascade,
  platform text not null,
  headline_en text,
  headline_es text,
  description_en text,
  description_es text,
  variation_type text,
  status text not null default 'draft',
  performance_score numeric(12,4),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists daily_metrics_client_date_idx on public.daily_metrics (client_id, metric_date desc);
create index if not exists optimization_runs_client_date_idx on public.optimization_runs (client_id, run_date desc);
create index if not exists ad_variations_client_status_idx on public.ad_variations (client_id, status);

alter table public.dashboard_clients enable row level security;
alter table public.ad_connections enable row level security;
alter table public.daily_metrics enable row level security;
alter table public.optimization_runs enable row level security;
alter table public.ad_variations enable row level security;

revoke all on public.dashboard_clients, public.ad_connections, public.daily_metrics, public.optimization_runs, public.ad_variations from anon, authenticated;
grant all on public.dashboard_clients, public.ad_connections, public.daily_metrics, public.optimization_runs, public.ad_variations to service_role;
grant usage, select on all sequences in schema public to service_role;
