// Comprehensive vehicle database for the quote estimator.
// Covers all major brands sold in California, with models and year ranges.
// Image convention: /vehicles/{brand}{model}{year}.png (lowercase, no spaces)
// e.g. /vehicles/bmwm32015.png

const CURRENT_YEAR = new Date().getFullYear() + 1; // includes next model year

function range(from, to) {
  const years = [];
  for (let y = from; y <= to; y++) years.push(y);
  return years;
}

export const VEHICLE_BRANDS = [
  {
    id: "acura",
    name: "Acura",
    models: [
      { id: "ilx", name: "ILX", years: range(2013, 2022) },
      { id: "integra", name: "Integra", years: range(2023, CURRENT_YEAR) },
      { id: "mdx", name: "MDX", years: range(2001, CURRENT_YEAR) },
      { id: "rdx", name: "RDX", years: range(2007, CURRENT_YEAR) },
      { id: "tlx", name: "TLX", years: range(2015, CURRENT_YEAR) },
      { id: "tsx", name: "TSX", years: range(2004, 2014) },
      { id: "rl", name: "RL", years: range(1996, 2012) },
      { id: "tl", name: "TL", years: range(1996, 2014) },
      { id: "rsx", name: "RSX", years: range(2002, 2006) },
      { id: "zdx", name: "ZDX", years: range(2024, CURRENT_YEAR) },
    ],
  },
  {
    id: "alfa-romeo",
    name: "Alfa Romeo",
    models: [
      { id: "giulia", name: "Giulia", years: range(2017, CURRENT_YEAR) },
      { id: "stelvio", name: "Stelvio", years: range(2018, CURRENT_YEAR) },
      { id: "tonale", name: "Tonale", years: range(2024, CURRENT_YEAR) },
    ],
  },
  {
    id: "audi",
    name: "Audi",
    models: [
      { id: "a3", name: "A3", years: range(2006, CURRENT_YEAR) },
      { id: "a4", name: "A4", years: range(1996, CURRENT_YEAR) },
      { id: "a5", name: "A5", years: range(2008, CURRENT_YEAR) },
      { id: "a6", name: "A6", years: range(1995, CURRENT_YEAR) },
      { id: "a7", name: "A7", years: range(2012, CURRENT_YEAR) },
      { id: "a8", name: "A8", years: range(1997, CURRENT_YEAR) },
      { id: "q3", name: "Q3", years: range(2015, CURRENT_YEAR) },
      { id: "q4-e-tron", name: "Q4 e-tron", years: range(2022, CURRENT_YEAR) },
      { id: "q5", name: "Q5", years: range(2009, CURRENT_YEAR) },
      { id: "q7", name: "Q7", years: range(2007, CURRENT_YEAR) },
      { id: "q8", name: "Q8", years: range(2019, CURRENT_YEAR) },
      { id: "e-tron-gt", name: "e-tron GT", years: range(2022, CURRENT_YEAR) },
      { id: "tt", name: "TT", years: range(2000, 2023) },
      { id: "r8", name: "R8", years: range(2008, 2024) },
      { id: "s4", name: "S4", years: range(2000, CURRENT_YEAR) },
      { id: "s5", name: "S5", years: range(2008, CURRENT_YEAR) },
      { id: "rs5", name: "RS 5", years: range(2013, CURRENT_YEAR) },
      { id: "sq5", name: "SQ5", years: range(2014, CURRENT_YEAR) },
    ],
  },
  {
    id: "bmw",
    name: "BMW",
    models: [
      { id: "2-series", name: "2 Series", years: range(2014, CURRENT_YEAR) },
      { id: "3-series", name: "3 Series", years: range(1992, CURRENT_YEAR) },
      { id: "4-series", name: "4 Series", years: range(2014, CURRENT_YEAR) },
      { id: "5-series", name: "5 Series", years: range(1990, CURRENT_YEAR) },
      { id: "7-series", name: "7 Series", years: range(1995, CURRENT_YEAR) },
      { id: "8-series", name: "8 Series", years: range(2019, CURRENT_YEAR) },
      { id: "x1", name: "X1", years: range(2013, CURRENT_YEAR) },
      { id: "x2", name: "X2", years: range(2018, CURRENT_YEAR) },
      { id: "x3", name: "X3", years: range(2004, CURRENT_YEAR) },
      { id: "x4", name: "X4", years: range(2015, CURRENT_YEAR) },
      { id: "x5", name: "X5", years: range(2000, CURRENT_YEAR) },
      { id: "x6", name: "X6", years: range(2008, CURRENT_YEAR) },
      { id: "x7", name: "X7", years: range(2019, CURRENT_YEAR) },
      { id: "xm", name: "XM", years: range(2023, CURRENT_YEAR) },
      { id: "z4", name: "Z4", years: range(2003, CURRENT_YEAR) },
      { id: "i4", name: "i4", years: range(2022, CURRENT_YEAR) },
      { id: "i5", name: "i5", years: range(2024, CURRENT_YEAR) },
      { id: "i7", name: "i7", years: range(2023, CURRENT_YEAR) },
      { id: "ix", name: "iX", years: range(2022, CURRENT_YEAR) },
      { id: "m3", name: "M3", years: range(1995, CURRENT_YEAR) },
      { id: "m4", name: "M4", years: range(2015, CURRENT_YEAR) },
      { id: "m5", name: "M5", years: range(1998, CURRENT_YEAR) },
    ],
  },
  {
    id: "buick",
    name: "Buick",
    models: [
      { id: "enclave", name: "Enclave", years: range(2008, CURRENT_YEAR) },
      { id: "encore", name: "Encore", years: range(2013, CURRENT_YEAR) },
      { id: "encore-gx", name: "Encore GX", years: range(2020, CURRENT_YEAR) },
      { id: "envista", name: "Envista", years: range(2024, CURRENT_YEAR) },
      { id: "envision", name: "Envision", years: range(2016, CURRENT_YEAR) },
      { id: "lacrosse", name: "LaCrosse", years: range(2005, 2019) },
      { id: "regal", name: "Regal", years: range(2011, 2020) },
    ],
  },
  {
    id: "cadillac",
    name: "Cadillac",
    models: [
      { id: "ct4", name: "CT4", years: range(2020, CURRENT_YEAR) },
      { id: "ct5", name: "CT5", years: range(2020, CURRENT_YEAR) },
      { id: "escalade", name: "Escalade", years: range(1999, CURRENT_YEAR) },
      { id: "xt4", name: "XT4", years: range(2019, CURRENT_YEAR) },
      { id: "xt5", name: "XT5", years: range(2017, CURRENT_YEAR) },
      { id: "xt6", name: "XT6", years: range(2020, CURRENT_YEAR) },
      { id: "lyriq", name: "LYRIQ", years: range(2023, CURRENT_YEAR) },
      { id: "cts", name: "CTS", years: range(2003, 2019) },
      { id: "srx", name: "SRX", years: range(2004, 2016) },
    ],
  },
  {
    id: "chevrolet",
    name: "Chevrolet",
    models: [
      { id: "blazer", name: "Blazer", years: range(2019, CURRENT_YEAR) },
      { id: "bolt-ev", name: "Bolt EV", years: range(2017, 2023) },
      { id: "bolt-euv", name: "Bolt EUV", years: range(2022, 2023) },
      { id: "camaro", name: "Camaro", years: range(2010, 2024) },
      { id: "colorado", name: "Colorado", years: range(2004, CURRENT_YEAR) },
      { id: "corvette", name: "Corvette", years: range(1997, CURRENT_YEAR) },
      { id: "cruze", name: "Cruze", years: range(2011, 2019) },
      { id: "equinox", name: "Equinox", years: range(2005, CURRENT_YEAR) },
      { id: "express", name: "Express", years: range(1996, CURRENT_YEAR) },
      { id: "impala", name: "Impala", years: range(2000, 2020) },
      { id: "malibu", name: "Malibu", years: range(1997, 2024) },
      { id: "silverado-1500", name: "Silverado 1500", years: range(1999, CURRENT_YEAR) },
      { id: "silverado-2500hd", name: "Silverado 2500HD", years: range(2001, CURRENT_YEAR) },
      { id: "silverado-3500hd", name: "Silverado 3500HD", years: range(2001, CURRENT_YEAR) },
      { id: "silverado-ev", name: "Silverado EV", years: range(2024, CURRENT_YEAR) },
      { id: "spark", name: "Spark", years: range(2013, 2022) },
      { id: "suburban", name: "Suburban", years: range(1992, CURRENT_YEAR) },
      { id: "tahoe", name: "Tahoe", years: range(1995, CURRENT_YEAR) },
      { id: "trailblazer", name: "Trailblazer", years: range(2021, CURRENT_YEAR) },
      { id: "traverse", name: "Traverse", years: range(2009, CURRENT_YEAR) },
      { id: "trax", name: "Trax", years: range(2015, CURRENT_YEAR) },
    ],
  },
  {
    id: "chrysler",
    name: "Chrysler",
    models: [
      { id: "300", name: "300", years: range(2005, 2023) },
      { id: "pacifica", name: "Pacifica", years: range(2017, CURRENT_YEAR) },
      { id: "voyager", name: "Voyager", years: range(2020, 2022) },
    ],
  },
  {
    id: "dodge",
    name: "Dodge",
    models: [
      { id: "challenger", name: "Challenger", years: range(2008, 2023) },
      { id: "charger", name: "Charger", years: range(2006, CURRENT_YEAR) },
      { id: "durango", name: "Durango", years: range(1998, CURRENT_YEAR) },
      { id: "grand-caravan", name: "Grand Caravan", years: range(1996, 2020) },
      { id: "hornet", name: "Hornet", years: range(2023, CURRENT_YEAR) },
      { id: "journey", name: "Journey", years: range(2009, 2020) },
    ],
  },
  {
    id: "fiat",
    name: "FIAT",
    models: [
      { id: "500", name: "500", years: range(2012, 2019) },
      { id: "500x", name: "500X", years: range(2016, 2023) },
      { id: "500e", name: "500e", years: range(2024, CURRENT_YEAR) },
    ],
  },
  {
    id: "ford",
    name: "Ford",
    models: [
      { id: "bronco", name: "Bronco", years: range(2021, CURRENT_YEAR) },
      { id: "bronco-sport", name: "Bronco Sport", years: range(2021, CURRENT_YEAR) },
      { id: "edge", name: "Edge", years: range(2007, 2024) },
      { id: "escape", name: "Escape", years: range(2001, CURRENT_YEAR) },
      { id: "expedition", name: "Expedition", years: range(1997, CURRENT_YEAR) },
      { id: "explorer", name: "Explorer", years: range(1991, CURRENT_YEAR) },
      { id: "f-150", name: "F-150", years: range(1992, CURRENT_YEAR) },
      { id: "f-150-lightning", name: "F-150 Lightning", years: range(2022, CURRENT_YEAR) },
      { id: "f-250", name: "F-250", years: range(1999, CURRENT_YEAR) },
      { id: "f-350", name: "F-350", years: range(1999, CURRENT_YEAR) },
      { id: "fiesta", name: "Fiesta", years: range(2011, 2019) },
      { id: "flex", name: "Flex", years: range(2009, 2019) },
      { id: "focus", name: "Focus", years: range(2000, 2018) },
      { id: "fusion", name: "Fusion", years: range(2006, 2020) },
      { id: "maverick", name: "Maverick", years: range(2022, CURRENT_YEAR) },
      { id: "mustang", name: "Mustang", years: range(1994, CURRENT_YEAR) },
      { id: "mustang-mach-e", name: "Mustang Mach-E", years: range(2021, CURRENT_YEAR) },
      { id: "ranger", name: "Ranger", years: range(1993, CURRENT_YEAR) },
      { id: "transit", name: "Transit", years: range(2015, CURRENT_YEAR) },
      { id: "transit-connect", name: "Transit Connect", years: range(2010, 2023) },
    ],
  },
  {
    id: "genesis",
    name: "Genesis",
    models: [
      { id: "g70", name: "G70", years: range(2019, CURRENT_YEAR) },
      { id: "g80", name: "G80", years: range(2017, CURRENT_YEAR) },
      { id: "g90", name: "G90", years: range(2017, CURRENT_YEAR) },
      { id: "gv60", name: "GV60", years: range(2023, CURRENT_YEAR) },
      { id: "gv70", name: "GV70", years: range(2022, CURRENT_YEAR) },
      { id: "gv80", name: "GV80", years: range(2021, CURRENT_YEAR) },
    ],
  },
  {
    id: "gmc",
    name: "GMC",
    models: [
      { id: "acadia", name: "Acadia", years: range(2007, CURRENT_YEAR) },
      { id: "canyon", name: "Canyon", years: range(2004, CURRENT_YEAR) },
      { id: "hummer-ev", name: "HUMMER EV", years: range(2022, CURRENT_YEAR) },
      { id: "savana", name: "Savana", years: range(1996, CURRENT_YEAR) },
      { id: "sierra-1500", name: "Sierra 1500", years: range(1999, CURRENT_YEAR) },
      { id: "sierra-2500hd", name: "Sierra 2500HD", years: range(2001, CURRENT_YEAR) },
      { id: "sierra-3500hd", name: "Sierra 3500HD", years: range(2001, CURRENT_YEAR) },
      { id: "terrain", name: "Terrain", years: range(2010, CURRENT_YEAR) },
      { id: "yukon", name: "Yukon", years: range(1992, CURRENT_YEAR) },
      { id: "yukon-xl", name: "Yukon XL", years: range(2000, CURRENT_YEAR) },
    ],
  },
  {
    id: "honda",
    name: "Honda",
    models: [
      { id: "accord", name: "Accord", years: range(1990, CURRENT_YEAR) },
      { id: "civic", name: "Civic", years: range(1990, CURRENT_YEAR) },
      { id: "cr-v", name: "CR-V", years: range(1997, CURRENT_YEAR) },
      { id: "element", name: "Element", years: range(2003, 2011) },
      { id: "fit", name: "Fit", years: range(2007, 2020) },
      { id: "hr-v", name: "HR-V", years: range(2016, CURRENT_YEAR) },
      { id: "insight", name: "Insight", years: range(2019, 2022) },
      { id: "odyssey", name: "Odyssey", years: range(1995, CURRENT_YEAR) },
      { id: "passport", name: "Passport", years: range(2019, CURRENT_YEAR) },
      { id: "pilot", name: "Pilot", years: range(2003, CURRENT_YEAR) },
      { id: "prologue", name: "Prologue", years: range(2024, CURRENT_YEAR) },
      { id: "ridgeline", name: "Ridgeline", years: range(2006, CURRENT_YEAR) },
    ],
  },
  {
    id: "hyundai",
    name: "Hyundai",
    models: [
      { id: "accent", name: "Accent", years: range(2000, 2022) },
      { id: "elantra", name: "Elantra", years: range(1996, CURRENT_YEAR) },
      { id: "ioniq-5", name: "IONIQ 5", years: range(2022, CURRENT_YEAR) },
      { id: "ioniq-6", name: "IONIQ 6", years: range(2023, CURRENT_YEAR) },
      { id: "kona", name: "Kona", years: range(2018, CURRENT_YEAR) },
      { id: "palisade", name: "Palisade", years: range(2020, CURRENT_YEAR) },
      { id: "santa-cruz", name: "Santa Cruz", years: range(2022, CURRENT_YEAR) },
      { id: "santa-fe", name: "Santa Fe", years: range(2001, CURRENT_YEAR) },
      { id: "sonata", name: "Sonata", years: range(1999, CURRENT_YEAR) },
      { id: "tucson", name: "Tucson", years: range(2005, CURRENT_YEAR) },
      { id: "venue", name: "Venue", years: range(2020, CURRENT_YEAR) },
      { id: "veloster", name: "Veloster", years: range(2012, 2021) },
    ],
  },
  {
    id: "infiniti",
    name: "INFINITI",
    models: [
      { id: "q50", name: "Q50", years: range(2014, CURRENT_YEAR) },
      { id: "q60", name: "Q60", years: range(2017, 2022) },
      { id: "qx50", name: "QX50", years: range(2014, CURRENT_YEAR) },
      { id: "qx55", name: "QX55", years: range(2022, CURRENT_YEAR) },
      { id: "qx60", name: "QX60", years: range(2013, CURRENT_YEAR) },
      { id: "qx80", name: "QX80", years: range(2011, CURRENT_YEAR) },
      { id: "g37", name: "G37", years: range(2008, 2013) },
    ],
  },
  {
    id: "jaguar",
    name: "Jaguar",
    models: [
      { id: "e-pace", name: "E-PACE", years: range(2018, 2024) },
      { id: "f-pace", name: "F-PACE", years: range(2017, CURRENT_YEAR) },
      { id: "f-type", name: "F-TYPE", years: range(2014, 2024) },
      { id: "xe", name: "XE", years: range(2017, 2020) },
      { id: "xf", name: "XF", years: range(2009, 2024) },
      { id: "i-pace", name: "I-PACE", years: range(2019, 2024) },
    ],
  },
  {
    id: "jeep",
    name: "Jeep",
    models: [
      { id: "cherokee", name: "Cherokee", years: range(2014, 2023) },
      { id: "compass", name: "Compass", years: range(2007, CURRENT_YEAR) },
      { id: "gladiator", name: "Gladiator", years: range(2020, CURRENT_YEAR) },
      { id: "grand-cherokee", name: "Grand Cherokee", years: range(1999, CURRENT_YEAR) },
      { id: "grand-cherokee-l", name: "Grand Cherokee L", years: range(2021, CURRENT_YEAR) },
      { id: "grand-wagoneer", name: "Grand Wagoneer", years: range(2022, CURRENT_YEAR) },
      { id: "renegade", name: "Renegade", years: range(2015, CURRENT_YEAR) },
      { id: "wagoneer", name: "Wagoneer", years: range(2022, CURRENT_YEAR) },
      { id: "wrangler", name: "Wrangler", years: range(1997, CURRENT_YEAR) },
    ],
  },
  {
    id: "kia",
    name: "Kia",
    models: [
      { id: "carnival", name: "Carnival", years: range(2022, CURRENT_YEAR) },
      { id: "ev6", name: "EV6", years: range(2022, CURRENT_YEAR) },
      { id: "ev9", name: "EV9", years: range(2024, CURRENT_YEAR) },
      { id: "forte", name: "Forte", years: range(2010, CURRENT_YEAR) },
      { id: "k5", name: "K5", years: range(2021, CURRENT_YEAR) },
      { id: "niro", name: "Niro", years: range(2017, CURRENT_YEAR) },
      { id: "optima", name: "Optima", years: range(2001, 2020) },
      { id: "rio", name: "Rio", years: range(2001, 2023) },
      { id: "seltos", name: "Seltos", years: range(2021, CURRENT_YEAR) },
      { id: "sorento", name: "Sorento", years: range(2003, CURRENT_YEAR) },
      { id: "soul", name: "Soul", years: range(2010, CURRENT_YEAR) },
      { id: "sportage", name: "Sportage", years: range(2005, CURRENT_YEAR) },
      { id: "stinger", name: "Stinger", years: range(2018, 2023) },
      { id: "telluride", name: "Telluride", years: range(2020, CURRENT_YEAR) },
    ],
  },
  {
    id: "land-rover",
    name: "Land Rover",
    models: [
      { id: "defender", name: "Defender", years: range(2020, CURRENT_YEAR) },
      { id: "discovery", name: "Discovery", years: range(2017, CURRENT_YEAR) },
      { id: "discovery-sport", name: "Discovery Sport", years: range(2015, CURRENT_YEAR) },
      { id: "range-rover", name: "Range Rover", years: range(2003, CURRENT_YEAR) },
      { id: "range-rover-evoque", name: "Range Rover Evoque", years: range(2012, CURRENT_YEAR) },
      { id: "range-rover-sport", name: "Range Rover Sport", years: range(2006, CURRENT_YEAR) },
      { id: "range-rover-velar", name: "Range Rover Velar", years: range(2018, CURRENT_YEAR) },
    ],
  },
  {
    id: "lexus",
    name: "Lexus",
    models: [
      { id: "es", name: "ES", years: range(1997, CURRENT_YEAR) },
      { id: "gx", name: "GX", years: range(2003, CURRENT_YEAR) },
      { id: "is", name: "IS", years: range(2001, CURRENT_YEAR) },
      { id: "lx", name: "LX", years: range(1996, CURRENT_YEAR) },
      { id: "nx", name: "NX", years: range(2015, CURRENT_YEAR) },
      { id: "rc", name: "RC", years: range(2015, CURRENT_YEAR) },
      { id: "rx", name: "RX", years: range(1999, CURRENT_YEAR) },
      { id: "rz", name: "RZ", years: range(2023, CURRENT_YEAR) },
      { id: "tx", name: "TX", years: range(2024, CURRENT_YEAR) },
      { id: "ux", name: "UX", years: range(2019, CURRENT_YEAR) },
      { id: "lc", name: "LC", years: range(2018, CURRENT_YEAR) },
    ],
  },
  {
    id: "lincoln",
    name: "Lincoln",
    models: [
      { id: "aviator", name: "Aviator", years: range(2020, CURRENT_YEAR) },
      { id: "corsair", name: "Corsair", years: range(2020, CURRENT_YEAR) },
      { id: "nautilus", name: "Nautilus", years: range(2019, CURRENT_YEAR) },
      { id: "navigator", name: "Navigator", years: range(1998, CURRENT_YEAR) },
      { id: "mkz", name: "MKZ", years: range(2006, 2020) },
      { id: "mkc", name: "MKC", years: range(2015, 2019) },
      { id: "mkx", name: "MKX", years: range(2007, 2018) },
    ],
  },
  {
    id: "maserati",
    name: "Maserati",
    models: [
      { id: "ghibli", name: "Ghibli", years: range(2014, 2023) },
      { id: "granturismo", name: "GranTurismo", years: range(2008, CURRENT_YEAR) },
      { id: "grecale", name: "Grecale", years: range(2023, CURRENT_YEAR) },
      { id: "levante", name: "Levante", years: range(2017, CURRENT_YEAR) },
      { id: "quattroporte", name: "Quattroporte", years: range(2005, 2023) },
    ],
  },
  {
    id: "mazda",
    name: "Mazda",
    models: [
      { id: "cx-30", name: "CX-30", years: range(2020, CURRENT_YEAR) },
      { id: "cx-5", name: "CX-5", years: range(2013, CURRENT_YEAR) },
      { id: "cx-50", name: "CX-50", years: range(2023, CURRENT_YEAR) },
      { id: "cx-70", name: "CX-70", years: range(2025, CURRENT_YEAR) },
      { id: "cx-9", name: "CX-9", years: range(2007, 2023) },
      { id: "cx-90", name: "CX-90", years: range(2024, CURRENT_YEAR) },
      { id: "mazda3", name: "Mazda3", years: range(2004, CURRENT_YEAR) },
      { id: "mazda6", name: "Mazda6", years: range(2003, 2021) },
      { id: "mx-5-miata", name: "MX-5 Miata", years: range(1990, CURRENT_YEAR) },
    ],
  },
  {
    id: "mercedes-benz",
    name: "Mercedes-Benz",
    models: [
      { id: "a-class", name: "A-Class", years: range(2019, 2022) },
      { id: "c-class", name: "C-Class", years: range(1994, CURRENT_YEAR) },
      { id: "cla", name: "CLA", years: range(2014, CURRENT_YEAR) },
      { id: "cls", name: "CLS", years: range(2006, 2024) },
      { id: "e-class", name: "E-Class", years: range(1996, CURRENT_YEAR) },
      { id: "eqb", name: "EQB", years: range(2022, CURRENT_YEAR) },
      { id: "eqe", name: "EQE", years: range(2023, CURRENT_YEAR) },
      { id: "eqs", name: "EQS", years: range(2022, CURRENT_YEAR) },
      { id: "g-class", name: "G-Class", years: range(2002, CURRENT_YEAR) },
      { id: "gla", name: "GLA", years: range(2015, CURRENT_YEAR) },
      { id: "glb", name: "GLB", years: range(2020, CURRENT_YEAR) },
      { id: "glc", name: "GLC", years: range(2016, CURRENT_YEAR) },
      { id: "gle", name: "GLE", years: range(2016, CURRENT_YEAR) },
      { id: "gls", name: "GLS", years: range(2017, CURRENT_YEAR) },
      { id: "s-class", name: "S-Class", years: range(2000, CURRENT_YEAR) },
      { id: "sl", name: "SL", years: range(2003, CURRENT_YEAR) },
      { id: "amg-gt", name: "AMG GT", years: range(2016, CURRENT_YEAR) },
    ],
  },
  {
    id: "mini",
    name: "MINI",
    models: [
      { id: "cooper", name: "Cooper", years: range(2002, CURRENT_YEAR) },
      { id: "countryman", name: "Countryman", years: range(2011, CURRENT_YEAR) },
      { id: "clubman", name: "Clubman", years: range(2008, 2024) },
    ],
  },
  {
    id: "mitsubishi",
    name: "Mitsubishi",
    models: [
      { id: "eclipse-cross", name: "Eclipse Cross", years: range(2018, CURRENT_YEAR) },
      { id: "mirage", name: "Mirage", years: range(2014, CURRENT_YEAR) },
      { id: "outlander", name: "Outlander", years: range(2007, CURRENT_YEAR) },
      { id: "outlander-sport", name: "Outlander Sport", years: range(2011, CURRENT_YEAR) },
    ],
  },
  {
    id: "nissan",
    name: "Nissan",
    models: [
      { id: "altima", name: "Altima", years: range(1998, CURRENT_YEAR) },
      { id: "ariya", name: "Ariya", years: range(2023, CURRENT_YEAR) },
      { id: "armada", name: "Armada", years: range(2004, CURRENT_YEAR) },
      { id: "frontier", name: "Frontier", years: range(1998, CURRENT_YEAR) },
      { id: "kicks", name: "Kicks", years: range(2018, CURRENT_YEAR) },
      { id: "leaf", name: "LEAF", years: range(2011, 2024) },
      { id: "maxima", name: "Maxima", years: range(1995, 2023) },
      { id: "murano", name: "Murano", years: range(2003, CURRENT_YEAR) },
      { id: "pathfinder", name: "Pathfinder", years: range(1996, CURRENT_YEAR) },
      { id: "rogue", name: "Rogue", years: range(2008, CURRENT_YEAR) },
      { id: "rogue-sport", name: "Rogue Sport", years: range(2017, 2022) },
      { id: "sentra", name: "Sentra", years: range(2000, CURRENT_YEAR) },
      { id: "titan", name: "Titan", years: range(2004, CURRENT_YEAR) },
      { id: "versa", name: "Versa", years: range(2007, CURRENT_YEAR) },
      { id: "z", name: "Z", years: range(2023, CURRENT_YEAR) },
      { id: "370z", name: "370Z", years: range(2009, 2020) },
    ],
  },
  {
    id: "porsche",
    name: "Porsche",
    models: [
      { id: "718-boxster", name: "718 Boxster", years: range(2017, CURRENT_YEAR) },
      { id: "718-cayman", name: "718 Cayman", years: range(2017, CURRENT_YEAR) },
      { id: "911", name: "911", years: range(1999, CURRENT_YEAR) },
      { id: "cayenne", name: "Cayenne", years: range(2003, CURRENT_YEAR) },
      { id: "macan", name: "Macan", years: range(2015, CURRENT_YEAR) },
      { id: "panamera", name: "Panamera", years: range(2010, CURRENT_YEAR) },
      { id: "taycan", name: "Taycan", years: range(2020, CURRENT_YEAR) },
    ],
  },
  {
    id: "ram",
    name: "RAM",
    models: [
      { id: "1500", name: "1500", years: range(2011, CURRENT_YEAR) },
      { id: "2500", name: "2500", years: range(2011, CURRENT_YEAR) },
      { id: "3500", name: "3500", years: range(2011, CURRENT_YEAR) },
      { id: "promaster", name: "ProMaster", years: range(2014, CURRENT_YEAR) },
      { id: "promaster-city", name: "ProMaster City", years: range(2015, 2022) },
    ],
  },
  {
    id: "rivian",
    name: "Rivian",
    models: [
      { id: "r1s", name: "R1S", years: range(2022, CURRENT_YEAR) },
      { id: "r1t", name: "R1T", years: range(2022, CURRENT_YEAR) },
    ],
  },
  {
    id: "subaru",
    name: "Subaru",
    models: [
      { id: "brz", name: "BRZ", years: range(2013, CURRENT_YEAR) },
      { id: "crosstrek", name: "Crosstrek", years: range(2013, CURRENT_YEAR) },
      { id: "forester", name: "Forester", years: range(1998, CURRENT_YEAR) },
      { id: "impreza", name: "Impreza", years: range(1993, CURRENT_YEAR) },
      { id: "legacy", name: "Legacy", years: range(1995, CURRENT_YEAR) },
      { id: "outback", name: "Outback", years: range(2000, CURRENT_YEAR) },
      { id: "solterra", name: "Solterra", years: range(2023, CURRENT_YEAR) },
      { id: "wrx", name: "WRX", years: range(2002, CURRENT_YEAR) },
      { id: "ascent", name: "Ascent", years: range(2019, CURRENT_YEAR) },
    ],
  },
  {
    id: "tesla",
    name: "Tesla",
    models: [
      { id: "model-3", name: "Model 3", years: range(2017, CURRENT_YEAR) },
      { id: "model-s", name: "Model S", years: range(2012, CURRENT_YEAR) },
      { id: "model-x", name: "Model X", years: range(2016, CURRENT_YEAR) },
      { id: "model-y", name: "Model Y", years: range(2020, CURRENT_YEAR) },
      { id: "cybertruck", name: "Cybertruck", years: range(2024, CURRENT_YEAR) },
    ],
  },
  {
    id: "toyota",
    name: "Toyota",
    models: [
      { id: "4runner", name: "4Runner", years: range(1996, CURRENT_YEAR) },
      { id: "86", name: "GR86", years: range(2022, CURRENT_YEAR) },
      { id: "avalon", name: "Avalon", years: range(1995, 2022) },
      { id: "bz4x", name: "bZ4X", years: range(2023, CURRENT_YEAR) },
      { id: "camry", name: "Camry", years: range(1992, CURRENT_YEAR) },
      { id: "corolla", name: "Corolla", years: range(1990, CURRENT_YEAR) },
      { id: "corolla-cross", name: "Corolla Cross", years: range(2022, CURRENT_YEAR) },
      { id: "crown", name: "Crown", years: range(2023, CURRENT_YEAR) },
      { id: "grand-highlander", name: "Grand Highlander", years: range(2024, CURRENT_YEAR) },
      { id: "gr-corolla", name: "GR Corolla", years: range(2023, CURRENT_YEAR) },
      { id: "gr-supra", name: "GR Supra", years: range(2020, CURRENT_YEAR) },
      { id: "highlander", name: "Highlander", years: range(2001, CURRENT_YEAR) },
      { id: "land-cruiser", name: "Land Cruiser", years: range(1998, CURRENT_YEAR) },
      { id: "prius", name: "Prius", years: range(2001, CURRENT_YEAR) },
      { id: "rav4", name: "RAV4", years: range(1996, CURRENT_YEAR) },
      { id: "sequoia", name: "Sequoia", years: range(2001, CURRENT_YEAR) },
      { id: "sienna", name: "Sienna", years: range(1998, CURRENT_YEAR) },
      { id: "tacoma", name: "Tacoma", years: range(1995, CURRENT_YEAR) },
      { id: "tundra", name: "Tundra", years: range(2000, CURRENT_YEAR) },
      { id: "venza", name: "Venza", years: range(2021, CURRENT_YEAR) },
      { id: "yaris", name: "Yaris", years: range(2007, 2020) },
    ],
  },
  {
    id: "volkswagen",
    name: "Volkswagen",
    models: [
      { id: "atlas", name: "Atlas", years: range(2018, CURRENT_YEAR) },
      { id: "atlas-cross-sport", name: "Atlas Cross Sport", years: range(2020, CURRENT_YEAR) },
      { id: "golf", name: "Golf", years: range(1999, CURRENT_YEAR) },
      { id: "golf-gti", name: "Golf GTI", years: range(2006, CURRENT_YEAR) },
      { id: "golf-r", name: "Golf R", years: range(2012, CURRENT_YEAR) },
      { id: "id4", name: "ID.4", years: range(2021, CURRENT_YEAR) },
      { id: "id-buzz", name: "ID. Buzz", years: range(2024, CURRENT_YEAR) },
      { id: "jetta", name: "Jetta", years: range(1999, CURRENT_YEAR) },
      { id: "jetta-gli", name: "Jetta GLI", years: range(2006, CURRENT_YEAR) },
      { id: "passat", name: "Passat", years: range(1998, 2022) },
      { id: "taos", name: "Taos", years: range(2022, CURRENT_YEAR) },
      { id: "tiguan", name: "Tiguan", years: range(2009, CURRENT_YEAR) },
    ],
  },
  {
    id: "volvo",
    name: "Volvo",
    models: [
      { id: "c40-recharge", name: "C40 Recharge", years: range(2022, CURRENT_YEAR) },
      { id: "ex30", name: "EX30", years: range(2024, CURRENT_YEAR) },
      { id: "ex90", name: "EX90", years: range(2024, CURRENT_YEAR) },
      { id: "s60", name: "S60", years: range(2001, CURRENT_YEAR) },
      { id: "s90", name: "S90", years: range(2017, CURRENT_YEAR) },
      { id: "v60", name: "V60", years: range(2019, CURRENT_YEAR) },
      { id: "v90", name: "V90", years: range(2017, 2024) },
      { id: "xc40", name: "XC40", years: range(2019, CURRENT_YEAR) },
      { id: "xc40-recharge", name: "XC40 Recharge", years: range(2021, CURRENT_YEAR) },
      { id: "xc60", name: "XC60", years: range(2010, CURRENT_YEAR) },
      { id: "xc90", name: "XC90", years: range(2003, CURRENT_YEAR) },
    ],
  },
  {
    id: "lucid",
    name: "Lucid",
    models: [
      { id: "air", name: "Air", years: range(2022, CURRENT_YEAR) },
      { id: "gravity", name: "Gravity", years: range(2025, CURRENT_YEAR) },
    ],
  },
  {
    id: "polestar",
    name: "Polestar",
    models: [
      { id: "polestar-2", name: "Polestar 2", years: range(2020, CURRENT_YEAR) },
      { id: "polestar-3", name: "Polestar 3", years: range(2024, CURRENT_YEAR) },
    ],
  },
];

export function getVehicleImagePath(brandId, modelId, year) {
  const slug = `${brandId}${modelId}${year}`.replace(/-/g, "");
  return `/vehicles/${slug}.png`;
}
