// Vehicle makes + models for the quote estimator.
// Model IDs are sanitised (lowercase, no spaces, no special chars) and double
// as the filename segment for vehicle photos in public/vehicles/:
//   {makeId}{modelId}{year}.png   e.g.  toyotacamry2020.png

const START_YEAR = 2000;

export const VEHICLE_YEARS = Array.from(
  { length: new Date().getFullYear() + 2 - START_YEAR },
  (_, i) => START_YEAR + i,
);

// Helper so image filenames are consistent everywhere.
// Tries .png first, then .webp so users can drop either format.
const IMG_EXTS = ["png", "webp", "jpg", "jpeg"];
export function vehicleImagePath(makeId, modelId, year, ext = "png") {
  return `/vehicles/${makeId}${modelId}${year}.${ext}`;
}
export function vehicleImageExts() {
  return IMG_EXTS;
}

export const MAKES = [
  {
    id: "acura",
    name: { en: "Acura", es: "Acura" },
    classId: "luxury_perf",
    models: [
      { id: "cl", label: { en: "CL", es: "CL" } },
      { id: "eldorado", label: { en: "Eldorado", es: "Eldorado" } },
      { id: "ilx", label: { en: "ILX", es: "ILX" } },
      { id: "integra", label: { en: "Integra", es: "Integra" } },
      { id: "legend", label: { en: "Legend", es: "Legend" } },
      { id: "mdx", label: { en: "MDX", es: "MDX" } },
      { id: "nsx", label: { en: "NSX", es: "NSX" } },
      { id: "rdx", label: { en: "RDX", es: "RDX" } },
      { id: "rl", label: { en: "RL", es: "RL" } },
      { id: "rlx", label: { en: "RLX", es: "RLX" } },
      { id: "rsx", label: { en: "RSX", es: "RSX" } },
      { id: "slx", label: { en: "SLX", es: "SLX" } },
      { id: "tl", label: { en: "TL", es: "TL" } },
      { id: "tlx", label: { en: "TLX", es: "TLX" } },
      { id: "tsx", label: { en: "TSX", es: "TSX" } },
      { id: "vigor", label: { en: "Vigor", es: "Vigor" } },
      { id: "zdx", label: { en: "ZDX", es: "ZDX" } },
    ],
  },
  {
    id: "alfaromeo",
    name: { en: "Alfa Romeo", es: "Alfa Romeo" },
    classId: "luxury_perf",
    models: [
      { id: "4c", label: { en: "4C", es: "4C" } },
      { id: "giulia", label: { en: "Giulia", es: "Giulia" } },
      { id: "stelvio", label: { en: "Stelvio", es: "Stelvio" } },
      { id: "tonale", label: { en: "Tonale", es: "Tonale" } },
    ],
  },
  {
    id: "astonmartin",
    name: { en: "Aston Martin", es: "Aston Martin" },
    classId: "luxury_perf",
    models: [
      { id: "db11", label: { en: "DB11", es: "DB11" } },
      { id: "db12", label: { en: "DB12", es: "DB12" } },
      { id: "db9", label: { en: "DB9", es: "DB9" } },
      { id: "dbs", label: { en: "DBS", es: "DBS" } },
      { id: "dbx", label: { en: "DBX", es: "DBX" } },
      { id: "rapide", label: { en: "Rapide", es: "Rapide" } },
      { id: "vantage", label: { en: "Vantage", es: "Vantage" } },
    ],
  },
  {
    id: "audi",
    name: { en: "Audi", es: "Audi" },
    classId: "luxury_perf",
    models: [
      { id: "a3", label: { en: "A3", es: "A3" } },
      { id: "a4", label: { en: "A4", es: "A4" } },
      { id: "a5", label: { en: "A5", es: "A5" } },
      { id: "a6", label: { en: "A6", es: "A6" } },
      { id: "a7", label: { en: "A7", es: "A7" } },
      { id: "a8", label: { en: "A8", es: "A8" } },
      { id: "allroad", label: { en: "Allroad", es: "Allroad" } },
      { id: "etron", label: { en: "e-tron", es: "e-tron" } },
      { id: "q3", label: { en: "Q3", es: "Q3" } },
      { id: "q5", label: { en: "Q5", es: "Q5" } },
      { id: "q7", label: { en: "Q7", es: "Q7" } },
      { id: "q8", label: { en: "Q8", es: "Q8" } },
      { id: "q4etron", label: { en: "Q4 e-tron", es: "Q4 e-tron" } },
      { id: "r8", label: { en: "R8", es: "R8" } },
      { id: "rs3", label: { en: "RS3", es: "RS3" } },
      { id: "rs5", label: { en: "RS5", es: "RS5" } },
      { id: "rs6", label: { en: "RS6", es: "RS6" } },
      { id: "s3", label: { en: "S3", es: "S3" } },
      { id: "s4", label: { en: "S4", es: "S4" } },
      { id: "s5", label: { en: "S5", es: "S5" } },
      { id: "sq5", label: { en: "SQ5", es: "SQ5" } },
      { id: "tt", label: { en: "TT", es: "TT" } },
    ],
  },
  {
    id: "bentley",
    name: { en: "Bentley", es: "Bentley" },
    classId: "luxury_perf",
    models: [
      { id: "bentayga", label: { en: "Bentayga", es: "Bentayga" } },
      { id: "continental", label: { en: "Continental GT", es: "Continental GT" } },
      { id: "flying", label: { en: "Flying Spur", es: "Flying Spur" } },
      { id: "mulsanne", label: { en: "Mulsanne", es: "Mulsanne" } },
    ],
  },
  {
    id: "bmw",
    name: { en: "BMW", es: "BMW" },
    classId: "luxury_perf",
    models: [
      { id: "2series", label: { en: "2 Series", es: "Serie 2" } },
      { id: "3series", label: { en: "3 Series", es: "Serie 3" } },
      { id: "4series", label: { en: "4 Series", es: "Serie 4" } },
      { id: "5series", label: { en: "5 Series", es: "Serie 5" } },
      { id: "6series", label: { en: "6 Series", es: "Serie 6" } },
      { id: "7series", label: { en: "7 Series", es: "Serie 7" } },
      { id: "8series", label: { en: "8 Series", es: "Serie 8" } },
      { id: "i3", label: { en: "i3", es: "i3" } },
      { id: "i4", label: { en: "i4", es: "i4" } },
      { id: "i5", label: { en: "i5", es: "i5" } },
      { id: "i7", label: { en: "i7", es: "i7" } },
      { id: "ix", label: { en: "iX", es: "iX" } },
      { id: "ix3", label: { en: "iX3", es: "iX3" } },
      { id: "m2", label: { en: "M2", es: "M2" } },
      { id: "m3", label: { en: "M3", es: "M3" } },
      { id: "m4", label: { en: "M4", es: "M4" } },
      { id: "m5", label: { en: "M5", es: "M5" } },
      { id: "m6", label: { en: "M6", es: "M6" } },
      { id: "m8", label: { en: "M8", es: "M8" } },
      { id: "x1", label: { en: "X1", es: "X1" } },
      { id: "x2", label: { en: "X2", es: "X2" } },
      { id: "x3", label: { en: "X3", es: "X3" } },
      { id: "x3m", label: { en: "X3 M", es: "X3 M" } },
      { id: "x4", label: { en: "X4", es: "X4" } },
      { id: "x4m", label: { en: "X4 M", es: "X4 M" } },
      { id: "x5", label: { en: "X5", es: "X5" } },
      { id: "x5m", label: { en: "X5 M", es: "X5 M" } },
      { id: "x6", label: { en: "X6", es: "X6" } },
      { id: "x6m", label: { en: "X6 M", es: "X6 M" } },
      { id: "x7", label: { en: "X7", es: "X7" } },
      { id: "xm", label: { en: "XM", es: "XM" } },
      { id: "z3", label: { en: "Z3", es: "Z3" } },
      { id: "z4", label: { en: "Z4", es: "Z4" } },
    ],
  },
  {
    id: "buick",
    name: { en: "Buick", es: "Buick" },
    classId: "sedan",
    models: [
      { id: "encore", label: { en: "Encore", es: "Encore" } },
      { id: "encoregx", label: { en: "Encore GX", es: "Encore GX" } },
      { id: "enclave", label: { en: "Enclave", es: "Enclave" } },
      { id: "envista", label: { en: "Envista", es: "Envista" } },
      { id: "lacrosse", label: { en: "LaCrosse", es: "LaCrosse" } },
      { id: "lucerne", label: { en: "Lucerne", es: "Lucerne" } },
      { id: "regal", label: { en: "Regal", es: "Regal" } },
      { id: "rendezvous", label: { en: "Rendezvous", es: "Rendezvous" } },
    ],
  },
  {
    id: "cadillac",
    name: { en: "Cadillac", es: "Cadillac" },
    classId: "luxury_perf",
    models: [
      { id: "ats", label: { en: "ATS", es: "ATS" } },
      { id: "celestiq", label: { en: "Celestiq", es: "Celestiq" } },
      { id: "cts", label: { en: "CTS", es: "CTS" } },
      { id: "dts", label: { en: "DTS", es: "DTS" } },
      { id: "eldorado", label: { en: "Eldorado", es: "Eldorado" } },
      { id: "escalade", label: { en: "Escalade", es: "Escalade" } },
      { id: "escaladev", label: { en: "Escalade-V", es: "Escalade-V" } },
      { id: "lyriq", label: { en: "LYRIQ", es: "LYRIQ" } },
      { id: "seville", label: { en: "Seville", es: "Seville" } },
      { id: "srx", label: { en: "SRX", es: "SRX" } },
      { id: "sts", label: { en: "STS", es: "STS" } },
      { id: "xt4", label: { en: "XT4", es: "XT4" } },
      { id: "xt5", label: { en: "XT5", es: "XT5" } },
      { id: "xt6", label: { en: "XT6", es: "XT6" } },
      { id: "xjr", label: { en: "XJR", es: "XJR" } },
    ],
  },
  {
    id: "chevrolet",
    name: { en: "Chevrolet", es: "Chevrolet" },
    classId: "sedan",
    models: [
      { id: "aveo", label: { en: "Aveo", es: "Aveo" } },
      { id: "blazer", label: { en: "Blazer", es: "Blazer" } },
      { id: "boltev", label: { en: "Bolt EV", es: "Bolt EV" } },
      { id: "bolteuv", label: { en: "Bolt EUV", es: "Bolt EUV" } },
      { id: "camaro", label: { en: "Camaro", es: "Camaro" } },
      { id: "caprice", label: { en: "Caprice", es: "Caprice" } },
      { id: "captiva", label: { en: "Captiva", es: "Captiva" } },
      { id: "cobalt", label: { en: "Cobalt", es: "Cobalt" } },
      { id: "colorado", label: { en: "Colorado", es: "Colorado" } },
      { id: "corvette", label: { en: "Corvette", es: "Corvette" } },
      { id: "cruze", label: { en: "Cruze", es: "Cruze" } },
      { id: "equinox", label: { en: "Equinox", es: "Equinox" } },
      { id: "express", label: { en: "Express", es: "Express" } },
      { id: "hhr", label: { en: "HHR", es: "HHR" } },
      { id: "impala", label: { en: "Impala", es: "Impala" } },
      { id: "lt", label: { en: "LUV", es: "LUV" } },
      { id: "malibu", label: { en: "Malibu", es: "Malibu" } },
      { id: "monte", label: { en: "Monte Carlo", es: "Monte Carlo" } },
      { id: "silverado1500", label: { en: "Silverado 1500", es: "Silverado 1500" } },
      { id: "silverado2500hd", label: { en: "Silverado 2500HD", es: "Silverado 2500HD" } },
      { id: "silverado3500hd", label: { en: "Silverado 3500HD", es: "Silverado 3500HD" } },
      { id: "spark", label: { en: "Spark", es: "Spark" } },
      { id: "ss", label: { en: "SS", es: "SS" } },
      { id: "suburban", label: { en: "Suburban", es: "Suburban" } },
      { id: "tahoe", label: { en: "Tahoe", es: "Tahoe" } },
      { id: "trailblazer", label: { en: "TrailBlazer", es: "TrailBlazer" } },
      { id: "traverse", label: { en: "Traverse", es: "Traverse" } },
      { id: "trax", label: { en: "Trax", es: "Trax" } },
      { id: "uplaander", label: { en: "Uplander", es: "Uplander" } },
      { id: "volt", label: { en: "Volt", es: "Volt" } },
    ],
  },
  {
    id: "chrysler",
    name: { en: "Chrysler", es: "Chrysler" },
    classId: "sedan",
    models: [
      { id: "200", label: { en: "200", es: "200" } },
      { id: "300", label: { en: "300", es: "300" } },
      { id: "aspen", label: { en: "Aspen", es: "Aspen" } },
      { id: "crossfire", label: { en: "Crossfire", es: "Crossfire" } },
      { id: "grandvoyager", label: { en: "Grand Voyager", es: "Grand Voyager" } },
      { id: "pacific", label: { en: "Pacific", es: "Pacific" } },
      { id: "ptcruiser", label: { en: "PT Cruiser", es: "PT Cruiser" } },
      { id: "sebring", label: { en: "Sebring", es: "Sebring" } },
      { id: "towncountry", label: { en: "Town & Country", es: "Town & Country" } },
      { id: "voyager", label: { en: "Voyager", es: "Voyager" } },
    ],
  },
  {
    id: "dodge",
    name: { en: "Dodge", es: "Dodge" },
    classId: "sedan",
    models: [
      { id: "avenger", label: { en: "Avenger", es: "Avenger" } },
      { id: "caliber", label: { en: "Caliber", es: "Caliber" } },
      { id: "caravan", label: { en: "Grand Caravan", es: "Grand Caravan" } },
      { id: "challenger", label: { en: "Challenger", es: "Challenger" } },
      { id: "charger", label: { en: "Charger", es: "Charger" } },
      { id: "dakota", label: { en: "Dakota", es: "Dakota" } },
      { id: "dart", label: { en: "Dart", es: "Dart" } },
      { id: "durango", label: { en: "Durango", es: "Durango" } },
      { id: "hornet", label: { en: "Hornet", es: "Hornet" } },
      { id: "intrepid", label: { en: "Intrepid", es: "Intrepid" } },
      { id: "journey", label: { en: "Journey", es: "Journey" } },
      { id: "magnum", label: { en: "Magnum", es: "Magnum" } },
      { id: "neon", label: { en: "Neon", es: "Neon" } },
      { id: "nitro", label: { en: "Nitro", es: "Nitro" } },
      { id: "ram1500", label: { en: "Ram 1500 (old)", es: "Ram 1500 (viejo)" } },
      { id: "ram2500", label: { en: "Ram 2500 (old)", es: "Ram 2500 (viejo)" } },
      { id: "viper", label: { en: "Viper", es: "Viper" } },
    ],
  },
  {
    id: "ferrari",
    name: { en: "Ferrari", es: "Ferrari" },
    classId: "luxury_perf",
    models: [
      { id: "296gtb", label: { en: "296 GTB", es: "296 GTB" } },
      { id: "458", label: { en: "458 Italia", es: "458 Italia" } },
      { id: "488", label: { en: "488 GTB", es: "488 GTB" } },
      { id: "812", label: { en: "812 Superfast", es: "812 Superfast" } },
      { id: "california", label: { en: "California", es: "California" } },
      { id: "f430", label: { en: "F430", es: "F430" } },
      { id: "ff", label: { en: "FF", es: "FF" } },
      { id: "gct4", label: { en: "GTC4Lusso", es: "GTC4Lusso" } },
      { id: "portofino", label: { en: "Portofino", es: "Portofino" } },
      { id: "roma", label: { en: "Roma", es: "Roma" } },
      { id: "sf90", label: { en: "SF90 Stradale", es: "SF90 Stradale" } },
      { id: "puro", label: { en: "Purosangue", es: "Purosangue" } },
    ],
  },
  {
    id: "fiat",
    name: { en: "Fiat", es: "Fiat" },
    classId: "compact",
    models: [
      { id: "124spider", label: { en: "124 Spider", es: "124 Spider" } },
      { id: "500", label: { en: "500", es: "500" } },
      { id: "500c", label: { en: "500c", es: "500c" } },
      { id: "500l", label: { en: "500L", es: "500L" } },
      { id: "500x", label: { en: "500X", es: "500X" } },
    ],
  },
  {
    id: "ford",
    name: { en: "Ford", es: "Ford" },
    classId: "sedan",
    models: [
      { id: "bronco", label: { en: "Bronco", es: "Bronco" } },
      { id: "broncosport", label: { en: "Bronco Sport", es: "Bronco Sport" } },
      { id: "cmaxt", label: { en: "C-MAX", es: "C-MAX" } },
      { id: "ecosport", label: { en: "EcoSport", es: "EcoSport" } },
      { id: "edge", label: { en: "Edge", es: "Edge" } },
      { id: "escape", label: { en: "Escape", es: "Escape" } },
      { id: "expedition", label: { en: "Expedition", es: "Expedition" } },
      { id: "explorer", label: { en: "Explorer", es: "Explorer" } },
      { id: "f150", label: { en: "F-150", es: "F-150" } },
      { id: "f250", label: { en: "F-250 Super Duty", es: "F-250 Super Duty" } },
      { id: "f350", label: { en: "F-350 Super Duty", es: "F-350 Super Duty" } },
      { id: "f450", label: { en: "F-450 Super Duty", es: "F-450 Super Duty" } },
      { id: "fiesta", label: { en: "Fiesta", es: "Fiesta" } },
      { id: "flex", label: { en: "Flex", es: "Flex" } },
      { id: "focus", label: { en: "Focus", es: "Focus" } },
      { id: "fusion", label: { en: "Fusion", es: "Fusion" } },
      { id: "mustang", label: { en: "Mustang", es: "Mustang" } },
      { id: "mustangmache", label: { en: "Mustang Mach-E", es: "Mustang Mach-E" } },
      { id: "ranger", label: { en: "Ranger", es: "Ranger" } },
      { id: "taurus", label: { en: "Taurus", es: "Taurus" } },
      { id: "thunderbird", label: { en: "Thunderbird", es: "Thunderbird" } },
      { id: "transit", label: { en: "Transit", es: "Transit" } },
      { id: "transitconnect", label: { en: "Transit Connect", es: "Transit Connect" } },
    ],
  },
  {
    id: "genesis",
    name: { en: "Genesis", es: "Genesis" },
    classId: "luxury_perf",
    models: [
      { id: "g70", label: { en: "G70", es: "G70" } },
      { id: "g80", label: { en: "G80", es: "G80" } },
      { id: "g90", label: { en: "G90", es: "G90" } },
      { id: "gv60", label: { en: "GV60", es: "GV60" } },
      { id: "gv70", label: { en: "GV70", es: "GV70" } },
      { id: "gv80", label: { en: "GV80", es: "GV80" } },
    ],
  },
  {
    id: "gmc",
    name: { en: "GMC", es: "GMC" },
    classId: "suv_truck",
    models: [
      { id: "acadia", label: { en: "Acadia", es: "Acadia" } },
      { id: "canyon", label: { en: "Canyon", es: "Canyon" } },
      { id: "envoy", label: { en: "Envoy", es: "Envoy" } },
      { id: "hummercanyonev", label: { en: "Hummer EV SUV", es: "Hummer EV SUV" } },
      { id: "hummerpickup", label: { en: "Hummer EV Pickup", es: "Hummer EV Pickup" } },
      { id: "safari", label: { en: "Safari", es: "Safari" } },
      { id: "savana", label: { en: "Savana", es: "Savana" } },
      { id: "sierra1500", label: { en: "Sierra 1500", es: "Sierra 1500" } },
      { id: "sierra2500hd", label: { en: "Sierra 2500HD", es: "Sierra 2500HD" } },
      { id: "sierra3500hd", label: { en: "Sierra 3500HD", es: "Sierra 3500HD" } },
      { id: "terrain", label: { en: "Terrain", es: "Terrain" } },
      { id: "yukon", label: { en: "Yukon", es: "Yukon" } },
      { id: "yukonxl", label: { en: "Yukon XL", es: "Yukon XL" } },
    ],
  },
  {
    id: "honda",
    name: { en: "Honda", es: "Honda" },
    classId: "sedan",
    models: [
      { id: "accord", label: { en: "Accord", es: "Accord" } },
      { id: "civic", label: { en: "Civic", es: "Civic" } },
      { id: "clarity", label: { en: "Clarity", es: "Clarity" } },
      { id: "crv", label: { en: "CR-V", es: "CR-V" } },
      { id: "crz", label: { en: "CR-Z", es: "CR-Z" } },
      { id: "element", label: { en: "Element", es: "Element" } },
      { id: "fit", label: { en: "Fit", es: "Fit" } },
      { id: "hrv", label: { en: "HR-V", es: "HR-V" } },
      { id: "insight", label: { en: "Insight", es: "Insight" } },
      { id: "odyssey", label: { en: "Odyssey", es: "Odyssey" } },
      { id: "passport", label: { en: "Passport", es: "Passport" } },
      { id: "pilot", label: { en: "Pilot", es: "Pilot" } },
      { id: "prologue", label: { en: "Prologue", es: "Prologue" } },
      { id: "ridgeline", label: { en: "Ridgeline", es: "Ridgeline" } },
      { id: "s2000", label: { en: "S2000", es: "S2000" } },
    ],
  },
  {
    id: "hummer",
    name: { en: "Hummer", es: "Hummer" },
    classId: "suv_truck",
    models: [
      { id: "h2", label: { en: "H2", es: "H2" } },
      { id: "h3", label: { en: "H3", es: "H3" } },
    ],
  },
  {
    id: "hyundai",
    name: { en: "Hyundai", es: "Hyundai" },
    classId: "sedan",
    models: [
      { id: "accents", label: { en: "Accent", es: "Accent" } },
      { id: "azera", label: { en: "Azera", es: "Azera" } },
      { id: "elantra", label: { en: "Elantra", es: "Elantra" } },
      { id: "elantragt", label: { en: "Elantra GT", es: "Elantra GT" } },
      { id: "equus", label: { en: "Equus", es: "Equus" } },
      { id: "genesis", label: { en: "Genesis", es: "Genesis" } },
      { id: "getz", label: { en: "Getz", es: "Getz" } },
      { id: "i10", label: { en: "i10", es: "i10" } },
      { id: "ioniq5", label: { en: "IONIQ 5", es: "IONIQ 5" } },
      { id: "ioniq6", label: { en: "IONIQ 6", es: "IONIQ 6" } },
      { id: "kona", label: { en: "Kona", es: "Kona" } },
      { id: "nexo", label: { en: "Nexo", es: "Nexo" } },
      { id: "palissade", label: { en: "Palisade", es: "Palisade" } },
      { id: "santafe", label: { en: "Santa Fe", es: "Santa Fe" } },
      { id: "sonata", label: { en: "Sonata", es: "Sonata" } },
      { id: "tucson", label: { en: "Tucson", es: "Tucson" } },
      { id: "veloster", label: { en: "Veloster", es: "Veloster" } },
      { id: "venue", label: { en: "Venue", es: "Venue" } },
    ],
  },
  {
    id: "infiniti",
    name: { en: "Infiniti", es: "Infiniti" },
    classId: "luxury_perf",
    models: [
      { id: "ex35", label: { en: "EX35", es: "EX35" } },
      { id: "fx35", label: { en: "FX35", es: "FX35" } },
      { id: "fx45", label: { en: "FX45", es: "FX45" } },
      { id: "g20", label: { en: "G20", es: "G20" } },
      { id: "g25", label: { en: "G25", es: "G25" } },
      { id: "g35", label: { en: "G35", es: "G35" } },
      { id: "g37", label: { en: "G37", es: "G37" } },
      { id: "i30", label: { en: "I30", es: "I30" } },
      { id: "i35", label: { en: "I35", es: "I35" } },
      { id: "j30", label: { en: "J30", es: "J30" } },
      { id: "jx35", label: { en: "JX35", es: "JX35" } },
      { id: "m35", label: { en: "M35", es: "M35" } },
      { id: "m37", label: { en: "M37", es: "M37" } },
      { id: "q30", label: { en: "Q30", es: "Q30" } },
      { id: "q40", label: { en: "Q40", es: "Q40" } },
      { id: "q50", label: { en: "Q50", es: "Q50" } },
      { id: "q60", label: { en: "Q60", es: "Q60" } },
      { id: "q70", label: { en: "Q70", es: "Q70" } },
      { id: "qx30", label: { en: "QX30", es: "QX30" } },
      { id: "qx4", label: { en: "QX4", es: "QX4" } },
      { id: "qx50", label: { en: "QX50", es: "QX50" } },
      { id: "qx55", label: { en: "QX55", es: "QX55" } },
      { id: "qx56", label: { en: "QX56", es: "QX56" } },
      { id: "qx60", label: { en: "QX60", es: "QX60" } },
      { id: "qx70", label: { en: "QX70", es: "QX70" } },
      { id: "qx80", label: { en: "QX80", es: "QX80" } },
    ],
  },
  {
    id: "jaguar",
    name: { en: "Jaguar", es: "Jaguar" },
    classId: "luxury_perf",
    models: [
      { id: "epace", label: { en: "E-Pace", es: "E-Pace" } },
      { id: "fpace", label: { en: "F-Pace", es: "F-Pace" } },
      { id: "ftype", label: { en: "F-Type", es: "F-Type" } },
      { id: "ipace", label: { en: "I-Pace", es: "I-Pace" } },
      { id: "s_type", label: { en: "S-Type", es: "S-Type" } },
      { id: "xf", label: { en: "XF", es: "XF" } },
      { id: "xj", label: { en: "XJ", es: "XJ" } },
      { id: "xj8", label: { en: "XJ8", es: "XJ8" } },
      { id: "xjs", label: { en: "XJS", es: "XJS" } },
      { id: "xk", label: { en: "XK", es: "XK" } },
      { id: "xkr", label: { en: "XKR", es: "XKR" } },
      { id: "xe", label: { en: "XE", es: "XE" } },
    ],
  },
  {
    id: "jeep",
    name: { en: "Jeep", es: "Jeep" },
    classId: "suv_truck",
    models: [
      { id: "cherokee", label: { en: "Cherokee", es: "Cherokee" } },
      { id: "cj5", label: { en: "CJ-5", es: "CJ-5" } },
      { id: "comanche", label: { en: "Comanche", es: "Comanche" } },
      { id: "commander", label: { en: "Commander", es: "Commander" } },
      { id: "compass", label: { en: "Compass", es: "Compass" } },
      { id: "gladiator", label: { en: "Gladiator", es: "Gladiator" } },
      { id: "grandcherokee", label: { en: "Grand Cherokee", es: "Grand Cherokee" } },
      { id: "liberty", label: { en: "Liberty", es: "Liberty" } },
      { id: "patriot", label: { en: "Patriot", es: "Patriot" } },
      { id: "renegade", label: { en: "Renegade", es: "Renegade" } },
      { id: "wagoneer", label: { en: "Wagoneer", es: "Wagoneer" } },
      { id: "wrangler", label: { en: "Wrangler", es: "Wrangler" } },
    ],
  },
  {
    id: "kia",
    name: { en: "Kia", es: "Kia" },
    classId: "sedan",
    models: [
      { id: "amanti", label: { en: "Amanti", es: "Amanti" } },
      { id: "borrego", label: { en: "Borrego", es: "Borrego" } },
      { id: "cadenza", label: { en: "Cadenza", es: "Cadenza" } },
      { id: "carnival", label: { en: "Carnival", es: "Carnival" } },
      { id: "ev6", label: { en: "EV6", es: "EV6" } },
      { id: "ev9", label: { en: "EV9", es: "EV9" } },
      { id: "forte", label: { en: "Forte", es: "Forte" } },
      { id: "k5", label: { en: "K5", es: "K5" } },
      { id: "niro", label: { en: "Niro", es: "Niro" } },
      { id: "optima", label: { en: "Optima", es: "Optima" } },
      { id: "rio", label: { en: "Rio", es: "Rio" } },
      { id: "sedona", label: { en: "Sedona", es: "Sedona" } },
      { id: "selltos", label: { en: "Seltos", es: "Seltos" } },
      { id: "sorento", label: { en: "Sorento", es: "Sorento" } },
      { id: "soul", label: { en: "Soul", es: "Soul" } },
      { id: "spectra", label: { en: "Spectra", es: "Spectra" } },
      { id: "sportage", label: { en: "Sportage", es: "Sportage" } },
      { id: "stinger", label: { en: "Stinger", es: "Stinger" } },
      { id: "telluride", label: { en: "Telluride", es: "Telluride" } },
    ],
  },
  {
    id: "lamborghini",
    name: { en: "Lamborghini", es: "Lamborghini" },
    classId: "luxury_perf",
    models: [
      { id: "aventador", label: { en: "Aventador", es: "Aventador" } },
      { id: "countach", label: { en: "Countach", es: "Countach" } },
      { id: "diablo", label: { en: "Diablo", es: "Diablo" } },
      { id: "gallardo", label: { en: "Gallardo", es: "Gallardo" } },
      { id: "huracan", label: { en: "Huracán", es: "Huracán" } },
      { id: "murcielago", label: { en: "Murciélago", es: "Murciélago" } },
      { id: "revuelto", label: { en: "Revuelto", es: "Revuelto" } },
      { id: "urus", label: { en: "Urus", es: "Urus" } },
    ],
  },
  {
    id: "landrover",
    name: { en: "Land Rover", es: "Land Rover" },
    classId: "luxury_perf",
    models: [
      { id: "defender", label: { en: "Defender", es: "Defender" } },
      { id: "discovery", label: { en: "Discovery", es: "Discovery" } },
      { id: "discoverysport", label: { en: "Discovery Sport", es: "Discovery Sport" } },
      { id: "evoque", label: { en: "Evoque", es: "Evoque" } },
      { id: "freelander", label: { en: "Freelander", es: "Freelander" } },
      { id: "range", label: { en: "Range Rover", es: "Range Rover" } },
      { id: "rangeevoque", label: { en: "Range Rover Evoque", es: "Range Rover Evoque" } },
      { id: "rangesport", label: { en: "Range Rover Sport", es: "Range Rover Sport" } },
      { id: "rangevelar", label: { en: "Range Rover Velar", es: "Range Rover Velar" } },
    ],
  },
  {
    id: "lexus",
    name: { en: "Lexus", es: "Lexus" },
    classId: "luxury_perf",
    models: [
      { id: "es250", label: { en: "ES 250", es: "ES 250" } },
      { id: "es300", label: { en: "ES 300", es: "ES 300" } },
      { id: "es330", label: { en: "ES 330", es: "ES 330" } },
      { id: "es350", label: { en: "ES 350", es: "ES 350" } },
      { id: "gs300", label: { en: "GS 300", es: "GS 300" } },
      { id: "gs350", label: { en: "GS 350", es: "GS 350" } },
      { id: "gs430", label: { en: "GS 430", es: "GS 430" } },
      { id: "gx460", label: { en: "GX 460", es: "GX 460" } },
      { id: "gx470", label: { en: "GX 470", es: "GX 470" } },
      { id: "hs250h", label: { en: "HS 250h", es: "HS 250h" } },
      { id: "is250", label: { en: "IS 250", es: "IS 250" } },
      { id: "is300", label: { en: "IS 300", es: "IS 300" } },
      { id: "is350", label: { en: "IS 350", es: "IS 350" } },
      { id: "lc500", label: { en: "LC 500", es: "LC 500" } },
      { id: "lfa", label: { en: "LFA", es: "LFA" } },
      { id: "ls400", label: { en: "LS 400", es: "LS 400" } },
      { id: "ls430", label: { en: "LS 430", es: "LS 430" } },
      { id: "ls460", label: { en: "LS 460", es: "LS 460" } },
      { id: "ls500", label: { en: "LS 500", es: "LS 500" } },
      { id: "lx470", label: { en: "LX 470", es: "LX 470" } },
      { id: "lx570", label: { en: "LX 570", es: "LX 570" } },
      { id: "lx600", label: { en: "LX 600", es: "LX 600" } },
      { id: "nx200t", label: { en: "NX 200t", es: "NX 200t" } },
      { id: "nx300h", label: { en: "NX 300h", es: "NX 300h" } },
      { id: "nx350h", label: { en: "NX 350h", es: "NX 350h" } },
      { id: "nx450h", label: { en: "NX 450h+", es: "NX 450h+" } },
      { id: "rc350", label: { en: "RC 350", es: "RC 350" } },
      { id: "rcf", label: { en: "RC F", es: "RC F" } },
      { id: "rx330", label: { en: "RX 330", es: "RX 330" } },
      { id: "rx350", label: { en: "RX 350", es: "RX 350" } },
      { id: "rx400h", label: { en: "RX 400h", es: "RX 400h" } },
      { id: "rx450h", label: { en: "RX 450h", es: "RX 450h" } },
      { id: "rx500", label: { en: "RX 500h", es: "RX 500h" } },
      { id: "rz450e", label: { en: "RZ 450e", es: "RZ 450e" } },
      { id: "sc430", label: { en: "SC 430", es: "SC 430" } },
      { id: "tx350", label: { en: "TX 350", es: "TX 350" } },
      { id: "ux200", label: { en: "UX 200", es: "UX 200" } },
      { id: "ux250h", label: { en: "UX 250h", es: "UX 250h" } },
    ],
  },
  {
    id: "lincoln",
    name: { en: "Lincoln", es: "Lincoln" },
    classId: "luxury_perf",
    models: [
      { id: "aviator", label: { en: "Aviator", es: "Aviator" } },
      { id: "blackwood", label: { en: "Blackwood", es: "Blackwood" } },
      { id: "continental", label: { en: "Continental", es: "Continental" } },
      { id: "corsair", label: { en: "Corsair", es: "Corsair" } },
      { id: "ls", label: { en: "LS", es: "LS" } },
      { id: "mkc", label: { en: "MKC", es: "MKC" } },
      { id: "mkd", label: { en: "MKS", es: "MKS" } },
      { id: "mkt", label: { en: "MKT", es: "MKT" } },
      { id: "mkx", label: { en: "MKX", es: "MKX" } },
      { id: "mkz", label: { en: "MKZ", es: "MKZ" } },
      { id: "navigator", label: { en: "Navigator", es: "Navigator" } },
      { id: "navigatorl", label: { en: "Navigator L", es: "Navigator L" } },
      { id: "ntilus", label: { en: "Nautilus", es: "Nautilus" } },
      { id: "towncar", label: { en: "Town Car", es: "Town Car" } },
      { id: "zephyr", label: { en: "Zephyr", es: "Zephyr" } },
    ],
  },
  {
    id: "lotus",
    name: { en: "Lotus", es: "Lotus" },
    classId: "luxury_perf",
    models: [
      { id: "eletre", label: { en: "Eletre", es: "Eletre" } },
      { id: "elis", label: { en: "Elise", es: "Elise" } },
      { id: "emira", label: { en: "Emira", es: "Emira" } },
      { id: "esprit", label: { en: "Esprit", es: "Esprit" } },
      { id: "evija", label: { en: "Evija", es: "Evija" } },
      { id: "exige", label: { en: "Exige", es: "Exige" } },
    ],
  },
  {
    id: "lucid",
    name: { en: "Lucid", es: "Lucid" },
    classId: "luxury_perf",
    models: [
      { id: "air", label: { en: "Air", es: "Air" } },
      { id: "gravity", label: { en: "Gravity", es: "Gravity" } },
    ],
  },
  {
    id: "maserati",
    name: { en: "Maserati", es: "Maserati" },
    classId: "luxury_perf",
    models: [
      { id: "ghibli", label: { en: "Ghibli", es: "Ghibli" } },
      { id: "grancabrio", label: { en: "GranCabrio", es: "GranCabrio" } },
      { id: "granturismo", label: { en: "GranTurismo", es: "GranTurismo" } },
      { id: "grecale", label: { en: "Grecale", es: "Grecale" } },
      { id: "levante", label: { en: "Levante", es: "Levante" } },
      { id: "mc20", label: { en: "MC20", es: "MC20" } },
      { id: "quattroporte", label: { en: "Quattroporte", es: "Quattroporte" } },
      { id: "spyder", label: { en: "Spyder", es: "Spyder" } },
    ],
  },
  {
    id: "mazda",
    name: { en: "Mazda", es: "Mazda" },
    classId: "sedan",
    models: [
      { id: "bt50", label: { en: "BT-50", es: "BT-50" } },
      { id: "cx30", label: { en: "CX-30", es: "CX-30" } },
      { id: "cx5", label: { en: "CX-5", es: "CX-5" } },
      { id: "cx50", label: { en: "CX-50", es: "CX-50" } },
      { id: "cx7", label: { en: "CX-7", es: "CX-7" } },
      { id: "cx9", label: { en: "CX-9", es: "CX-9" } },
      { id: "cx90", label: { en: "CX-90", es: "CX-90" } },
      { id: "mazda2", label: { en: "Mazda2", es: "Mazda2" } },
      { id: "mazda3", label: { en: "Mazda3", es: "Mazda3" } },
      { id: "mazda5", label: { en: "Mazda5", es: "Mazda5" } },
      { id: "mazda6", label: { en: "Mazda6", es: "Mazda6" } },
      { id: "miata", label: { en: "MX-5 Miata", es: "MX-5 Miata" } },
      { id: "protege", label: { en: "Protegé", es: "Protegé" } },
      { id: "rx8", label: { en: "RX-8", es: "RX-8" } },
      { id: "tribute", label: { en: "Tribute", es: "Tribute" } },
    ],
  },
  {
    id: "mclaren",
    name: { en: "McLaren", es: "McLaren" },
    classId: "luxury_perf",
    models: [
      { id: "570s", label: { en: "570S", es: "570S" } },
      { id: "600lt", label: { en: "600LT", es: "600LT" } },
      { id: "720s", label: { en: "720S", es: "720S" } },
      { id: "765lt", label: { en: "765LT", es: "765LT" } },
      { id: "artura", label: { en: "Artura", es: "Artura" } },
      { id: "gt", label: { en: "GT", es: "GT" } },
      { id: "mp412c", label: { en: "MP4-12C", es: "MP4-12C" } },
      { id: "p1", label: { en: "P1", es: "P1" } },
      { id: "senna", label: { en: "Senna", es: "Senna" } },
    ],
  },
  {
    id: "mercedesbenz",
    name: { en: "Mercedes-Benz", es: "Mercedes-Benz" },
    classId: "luxury_perf",
    models: [
      { id: "aclass", label: { en: "A-Class", es: "Clase A" } },
      { id: "amggt", label: { en: "AMG GT", es: "AMG GT" } },
      { id: "cclass", label: { en: "C-Class", es: "Clase C" } },
      { id: "clclass", label: { en: "CL-Class", es: "Clase CL" } },
      { id: "cla", label: { en: "CLA", es: "CLA" } },
      { id: "cls", label: { en: "CLS", es: "CLS" } },
      { id: "eclass", label: { en: "E-Class", es: "Clase E" } },
      { id: "eqc", label: { en: "EQC", es: "EQC" } },
      { id: "eqe", label: { en: "EQE", es: "EQE" } },
      { id: "eqs", label: { en: "EQS", es: "EQS" } },
      { id: "eqssuv", label: { en: "EQS SUV", es: "EQS SUV" } },
      { id: "gclass", label: { en: "G-Class", es: "Clase G" } },
      { id: "glclass", label: { en: "GL-Class", es: "Clase GL" } },
      { id: "gla", label: { en: "GLA", es: "GLA" } },
      { id: "glb", label: { en: "GLB", es: "GLB" } },
      { id: "gle", label: { en: "GLE", es: "GLE" } },
      { id: "glk", label: { en: "GLK", es: "GLK" } },
      { id: "mlclass", label: { en: "M-Class", es: "Clase M" } },
      { id: "rclass", label: { en: "R-Class", es: "Clase R" } },
      { id: "sclass", label: { en: "S-Class", es: "Clase S" } },
      { id: "sl", label: { en: "SL", es: "SL" } },
      { id: "slk", label: { en: "SLK", es: "SLK" } },
      { id: "sls", label: { en: "SLS AMG", es: "SLS AMG" } },
      { id: "sprinter", label: { en: "Sprinter", es: "Sprinter" } },
    ],
  },
  {
    id: "mini",
    name: { en: "MINI", es: "MINI" },
    classId: "compact",
    models: [
      { id: "clubman", label: { en: "Clubman", es: "Clubman" } },
      { id: "convertible", label: { en: "Convertible", es: "Convertible" } },
      { id: "countryman", label: { en: "Countryman", es: "Countryman" } },
      { id: "coupe", label: { en: "Coupé", es: "Coupé" } },
      { id: "hardtop", label: { en: "Hardtop", es: "Hardtop" } },
      { id: "paceman", label: { en: "Paceman", es: "Paceman" } },
      { id: "roadster", label: { en: "Roadster", es: "Roadster" } },
    ],
  },
  {
    id: "mitsubishi",
    name: { en: "Mitsubishi", es: "Mitsubishi" },
    classId: "sedan",
    models: [
      { id: "eclipse", label: { en: "Eclipse", es: "Eclipse" } },
      { id: "eclipsecross", label: { en: "Eclipse Cross", es: "Eclipse Cross" } },
      { id: "endurance", label: { en: "Endeavor", es: "Endeavor" } },
      { id: "galant", label: { en: "Galant", es: "Galant" } },
      { id: "lancer", label: { en: "Lancer", es: "Lancer" } },
      { id: "mirage", label: { en: "Mirage", es: "Mirage" } },
      { id: "montero", label: { en: "Montero", es: "Montero" } },
      { id: "outlander", label: { en: "Outlander", es: "Outlander" } },
      { id: "outlandersport", label: { en: "Outlander Sport", es: "Outlander Sport" } },
    ],
  },
  {
    id: "nissan",
    name: { en: "Nissan", es: "Nissan" },
    classId: "sedan",
    models: [
      { id: "altima", label: { en: "Altima", es: "Altima" } },
      { id: "armada", label: { en: "Armada", es: "Armada" } },
      { id: "cube", label: { en: "Cube", es: "Cube" } },
      { id: "frontier", label: { en: "Frontier", es: "Frontier" } },
      { id: "gt", label: { en: "GT-R", es: "GT-R" } },
      { id: "juke", label: { en: "Juke", es: "Juke" } },
      { id: "kicks", label: { en: "Kicks", es: "Kicks" } },
      { id: "leaf", label: { en: "Leaf", es: "Leaf" } },
      { id: "maxima", label: { en: "Maxima", es: "Maxima" } },
      { id: "murano", label: { en: "Murano", es: "Murano" } },
      { id: "nv", label: { en: "NV", es: "NV" } },
      { id: "nv200", label: { en: "NV200", es: "NV200" } },
      { id: "pathfinder", label: { en: "Pathfinder", es: "Pathfinder" } },
      { id: "quest", label: { en: "Quest", es: "Quest" } },
      { id: "rogue", label: { en: "Rogue", es: "Rogue" } },
      { id: "sentra", label: { en: "Sentra", es: "Sentra" } },
      { id: "titan", label: { en: "Titan", es: "Titan" } },
      { id: "versa", label: { en: "Versa", es: "Versa" } },
      { id: "xterra", label: { en: "Xterra", es: "Xterra" } },
      { id: "z", label: { en: "Z", es: "Z" } },
      { id: "350z", label: { en: "350Z", es: "350Z" } },
      { id: "370z", label: { en: "370Z", es: "370Z" } },
    ],
  },
  {
    id: "polestar",
    name: { en: "Polestar", es: "Polestar" },
    classId: "luxury_perf",
    models: [
      { id: "1", label: { en: "1", es: "1" } },
      { id: "2", label: { en: "2", es: "2" } },
      { id: "3", label: { en: "3", es: "3" } },
      { id: "4", label: { en: "4", es: "4" } },
    ],
  },
  {
    id: "porsche",
    name: { en: "Porsche", es: "Porsche" },
    classId: "luxury_perf",
    models: [
      { id: "718boxster", label: { en: "718 Boxster", es: "718 Boxster" } },
      { id: "718cayman", label: { en: "718 Cayman", es: "718 Cayman" } },
      { id: "911", label: { en: "911", es: "911" } },
      { id: "944", label: { en: "944", es: "944" } },
      { id: "boxster", label: { en: "Boxster", es: "Boxster" } },
      { id: "cayenne", label: { en: "Cayenne", es: "Cayenne" } },
      { id: "cayman", label: { en: "Cayman", es: "Cayman" } },
      { id: "macan", label: { en: "Macan", es: "Macan" } },
      { id: "panamera", label: { en: "Panamera", es: "Panamera" } },
      { id: "taycan", label: { en: "Taycan", es: "Taycan" } },
    ],
  },
  {
    id: "ram",
    name: { en: "Ram", es: "Ram" },
    classId: "suv_truck",
    models: [
      { id: "1500", label: { en: "1500", es: "1500" } },
      { id: "2500", label: { en: "2500", es: "2500" } },
      { id: "3500", label: { en: "3500", es: "3500" } },
      { id: "4500", label: { en: "4500", es: "4500" } },
      { id: "5500", label: { en: "5500", es: "5500" } },
      { id: "promaster", label: { en: "ProMaster", es: "ProMaster" } },
      { id: "promastercity", label: { en: "ProMaster City", es: "ProMaster City" } },
    ],
  },
  {
    id: "rivian",
    name: { en: "Rivian", es: "Rivian" },
    classId: "suv_truck",
    models: [
      { id: "r1s", label: { en: "R1S", es: "R1S" } },
      { id: "r1t", label: { en: "R1T", es: "R1T" } },
    ],
  },
  {
    id: "rollsroyce",
    name: { en: "Rolls-Royce", es: "Rolls-Royce" },
    classId: "luxury_perf",
    models: [
      { id: "cullinan", label: { en: "Cullinan", es: "Cullinan" } },
      { id: "dawn", label: { en: "Dawn", es: "Dawn" } },
      { id: "ghost", label: { en: "Ghost", es: "Ghost" } },
      { id: "phantom", label: { en: "Phantom", es: "Phantom" } },
      { id: "spect", label: { en: "Spectre", es: "Spectre" } },
      { id: "wraith", label: { en: "Wraith", es: "Wraith" } },
    ],
  },
  {
    id: "saab",
    name: { en: "Saab", es: "Saab" },
    classId: "sedan",
    models: [
      { id: "93", label: { en: "9-3", es: "9-3" } },
      { id: "95", label: { en: "9-5", es: "9-5" } },
    ],
  },
  {
    id: "saturn",
    name: { en: "Saturn", es: "Saturn" },
    classId: "sedan",
    models: [
      { id: "aura", label: { en: "Aura", es: "Aura" } },
      { id: "ion", label: { en: "ION", es: "ION" } },
      { id: "l200", label: { en: "L-Series", es: "L-Series" } },
      { id: "outlook", label: { en: "Outlook", es: "Outlook" } },
      { id: "relay", label: { en: "Relay", es: "Relay" } },
      { id: "sky", label: { en: "Sky", es: "Sky" } },
      { id: "sline", label: { en: "S-Series", es: "S-Series" } },
      { id: "vue", label: { en: "VUE", es: "VUE" } },
    ],
  },
  {
    id: "scion",
    name: { en: "Scion", es: "Scion" },
    classId: "compact",
    models: [
      { id: "fr", label: { en: "FR-S", es: "FR-S" } },
      { id: "ia", label: { en: "iA", es: "iA" } },
      { id: "ib", label: { en: "iM", es: "iM" } },
      { id: "iq", label: { en: "iQ", es: "iQ" } },
      { id: "tc", label: { en: "tC", es: "tC" } },
      { id: "xa", label: { en: "xA", es: "xA" } },
      { id: "xb", label: { en: "xB", es: "xB" } },
      { id: "xd", label: { en: "xD", es: "xD" } },
    ],
  },
  {
    id: "smart",
    name: { en: "Smart", es: "Smart" },
    classId: "compact",
    models: [
      { id: "eqfortwo", label: { en: "EQ ForTwo", es: "EQ ForTwo" } },
      { id: "fortwo", label: { en: "ForTwo", es: "ForTwo" } },
    ],
  },
  {
    id: "subaru",
    name: { en: "Subaru", es: "Subaru" },
    classId: "sedan",
    models: [
      { id: "ascent", label: { en: "Ascent", es: "Ascent" } },
      { id: "baja", label: { en: "Baja", es: "Baja" } },
      { id: "brz", label: { en: "BRZ", es: "BRZ" } },
      { id: "crosstrek", label: { en: "Crosstrek", es: "Crosstrek" } },
      { id: "forester", label: { en: "Forester", es: "Forester" } },
      { id: "impreza", label: { en: "Impreza", es: "Impreza" } },
      { id: "legacy", label: { en: "Legacy", es: "Legacy" } },
      { id: "outback", label: { en: "Outback", es: "Outback" } },
      { id: "solterra", label: { en: "Solterra", es: "Solterra" } },
      { id: "tribeca", label: { en: "Tribeca", es: "Tribeca" } },
      { id: "wrx", label: { en: "WRX", es: "WRX" } },
      { id: "xv", label: { en: "XV", es: "XV" } },
    ],
  },
  {
    id: "suzuki",
    name: { en: "Suzuki", es: "Suzuki" },
    classId: "compact",
    models: [
      { id: "aerio", label: { en: "Aerio", es: "Aerio" } },
      { id: "equator", label: { en: "Equator", es: "Equator" } },
      { id: "grandvitara", label: { en: "Grand Vitara", es: "Grand Vitara" } },
      { id: "kizashi", label: { en: "Kizashi", es: "Kizashi" } },
      { id: "sx4", label: { en: "SX4", es: "SX4" } },
      { id: "swift", label: { en: "Swift", es: "Swift" } },
      { id: "vitara", label: { en: "Vitara", es: "Vitara" } },
    ],
  },
  {
    id: "tesla",
    name: { en: "Tesla", es: "Tesla" },
    classId: "luxury_perf",
    models: [
      { id: "cybertruck", label: { en: "Cybertruck", es: "Cybertruck" } },
      { id: "model3", label: { en: "Model 3", es: "Model 3" } },
      { id: "models", label: { en: "Model S", es: "Model S" } },
      { id: "modelx", label: { en: "Model X", es: "Model X" } },
      { id: "modely", label: { en: "Model Y", es: "Model Y" } },
      { id: "roadster", label: { en: "Roadster", es: "Roadster" } },
    ],
  },
  {
    id: "toyota",
    name: { en: "Toyota", es: "Toyota" },
    classId: "sedan",
    models: [
      { id: "4runner", label: { en: "4Runner", es: "4Runner" } },
      { id: "avalon", label: { en: "Avalon", es: "Avalon" } },
      { id: "camry", label: { en: "Camry", es: "Camry" } },
      { id: "celica", label: { en: "Celica", es: "Celica" } },
      { id: "corolla", label: { en: "Corolla", es: "Corolla" } },
      { id: "cressida", label: { en: "Cressida", es: "Cressida" } },
      { id: "crown", label: { en: "Crown", es: "Crown" } },
      { id: "fjcruiser", label: { en: "FJ Cruiser", es: "FJ Cruiser" } },
      { id: "grandhighlander", label: { en: "Grand Highlander", es: "Grand Highlander" } },
      { id: "highlander", label: { en: "Highlander", es: "Highlander" } },
      { id: "hilux", label: { en: "Hilux", es: "Hilux" } },
      { id: "landcruiser", label: { en: "Land Cruiser", es: "Land Cruiser" } },
      { id: "matrix", label: { en: "Matrix", es: "Matrix" } },
      { id: "mirai", label: { en: "Mirai", es: "Mirai" } },
      { id: "mr2", label: { en: "MR2", es: "MR2" } },
      { id: "prius", label: { en: "Prius", es: "Prius" } },
      { id: "rav4", label: { en: "RAV4", es: "RAV4" } },
      { id: "seguoia", label: { en: "Sequoia", es: "Sequoia" } },
      { id: "sienna", label: { en: "Sienna", es: "Sienna" } },
      { id: "solara", label: { en: "Solara", es: "Solara" } },
      { id: "supra", label: { en: "Supra", es: "Supra" } },
      { id: "tacoma", label: { en: "Tacoma", es: "Tacoma" } },
      { id: "tundra", label: { en: "Tundra", es: "Tundra" } },
      { id: "venza", label: { en: "Venza", es: "Venza" } },
      { id: "yaris", label: { en: "Yaris", es: "Yaris" } },
    ],
  },
  {
    id: "volkswagen",
    name: { en: "Volkswagen", es: "Volkswagen" },
    classId: "sedan",
    models: [
      { id: "atlas", label: { en: "Atlas", es: "Atlas" } },
      { id: "beetle", label: { en: "Beetle", es: "Beetle" } },
      { id: "cc", label: { en: "CC", es: "CC" } },
      { id: "eos", label: { en: "Eos", es: "Eos" } },
      { id: "golf", label: { en: "Golf", es: "Golf" } },
      { id: "golfgti", label: { en: "Golf GTI", es: "Golf GTI" } },
      { id: "golfr", label: { en: "Golf R", es: "Golf R" } },
      { id: "id4", label: { en: "ID.4", es: "ID.4" } },
      { id: "jetta", label: { en: "Jetta", es: "Jetta" } },
      { id: "passat", label: { en: "Passat", es: "Passat" } },
      { id: "phaeton", label: { en: "Phaeton", es: "Phaeton" } },
      { id: "rabbit", label: { en: "Rabbit", es: "Rabbit" } },
      { id: "roush", label: { en: "Routan", es: "Routan" } },
      { id: "tiguan", label: { en: "Tiguan", es: "Tiguan" } },
      { id: "touareg", label: { en: "Touareg", es: "Touareg" } },
    ],
  },
  {
    id: "volvo",
    name: { en: "Volvo", es: "Volvo" },
    classId: "luxury_perf",
    models: [
      { id: "c30", label: { en: "C30", es: "C30" } },
      { id: "c40", label: { en: "C40 Recharge", es: "C40 Recharge" } },
      { id: "c70", label: { en: "C70", es: "C70" } },
      { id: "ex30", label: { en: "EX30", es: "EX30" } },
      { id: "ex90", label: { en: "EX90", es: "EX90" } },
      { id: "s40", label: { en: "S40", es: "S40" } },
      { id: "s60", label: { en: "S60", es: "S60" } },
      { id: "s80", label: { en: "S80", es: "S80" } },
      { id: "s90", label: { en: "S90", es: "S90" } },
      { id: "v40", label: { en: "V40", es: "V40" } },
      { id: "v50", label: { en: "V50", es: "V50" } },
      { id: "v60", label: { en: "V60", es: "V60" } },
      { id: "v70", label: { en: "V70", es: "V70" } },
      { id: "v90", label: { en: "V90", es: "V90" } },
      { id: "xc40", label: { en: "XC40", es: "XC40" } },
      { id: "xc60", label: { en: "XC60", es: "XC60" } },
      { id: "xc70", label: { en: "XC70", es: "XC70" } },
      { id: "xc90", label: { en: "XC90", es: "XC90" } },
    ],
  },
];

// --- Extended brand/model/year catalog used by the /quote vehicle image picker ---
const CURRENT_YEAR = new Date().getFullYear() + 1; // includes next model year

function range(from, to) {
  const years = [];
  for (let y = from; y <= to; y++) years.push(y);
  return years;
}

export const VEHICLE_BRANDS = [
  {
    id: "acura",
    name: "Acura",
    models: [
      { id: "ilx", name: "ILX", years: range(2013, 2022) },
      { id: "integra", name: "Integra", years: range(2023, CURRENT_YEAR) },
      { id: "mdx", name: "MDX", years: range(2001, CURRENT_YEAR) },
      { id: "rdx", name: "RDX", years: range(2007, CURRENT_YEAR) },
      { id: "tlx", name: "TLX", years: range(2015, CURRENT_YEAR) },
      { id: "tsx", name: "TSX", years: range(2004, 2014) },
      { id: "rl", name: "RL", years: range(1996, 2012) },
      { id: "tl", name: "TL", years: range(1996, 2014) },
      { id: "rsx", name: "RSX", years: range(2002, 2006) },
      { id: "zdx", name: "ZDX", years: range(2024, CURRENT_YEAR) },
    ],
  },
  {
    id: "alfa-romeo",
    name: "Alfa Romeo",
    models: [
      { id: "giulia", name: "Giulia", years: range(2017, CURRENT_YEAR) },
      { id: "stelvio", name: "Stelvio", years: range(2018, CURRENT_YEAR) },
      { id: "tonale", name: "Tonale", years: range(2024, CURRENT_YEAR) },
    ],
  },
  {
    id: "audi",
    name: "Audi",
    models: [
      { id: "a3", name: "A3", years: range(2006, CURRENT_YEAR) },
      { id: "a4", name: "A4", years: range(1996, CURRENT_YEAR) },
      { id: "a5", name: "A5", years: range(2008, CURRENT_YEAR) },
      { id: "a6", name: "A6", years: range(1995, CURRENT_YEAR) },
      { id: "a7", name: "A7", years: range(2012, CURRENT_YEAR) },
      { id: "a8", name: "A8", years: range(1997, CURRENT_YEAR) },
      { id: "q3", name: "Q3", years: range(2015, CURRENT_YEAR) },
      { id: "q4-e-tron", name: "Q4 e-tron", years: range(2022, CURRENT_YEAR) },
      { id: "q5", name: "Q5", years: range(2009, CURRENT_YEAR) },
      { id: "q7", name: "Q7", years: range(2007, CURRENT_YEAR) },
      { id: "q8", name: "Q8", years: range(2019, CURRENT_YEAR) },
      { id: "e-tron-gt", name: "e-tron GT", years: range(2022, CURRENT_YEAR) },
      { id: "tt", name: "TT", years: range(2000, 2023) },
      { id: "r8", name: "R8", years: range(2008, 2024) },
      { id: "s4", name: "S4", years: range(2000, CURRENT_YEAR) },
      { id: "s5", name: "S5", years: range(2008, CURRENT_YEAR) },
      { id: "rs5", name: "RS 5", years: range(2013, CURRENT_YEAR) },
      { id: "sq5", name: "SQ5", years: range(2014, CURRENT_YEAR) },
    ],
  },
  {
    id: "bmw",
    name: "BMW",
    models: [
      { id: "2-series", name: "2 Series", years: range(2014, CURRENT_YEAR) },
      { id: "3-series", name: "3 Series", years: range(1992, CURRENT_YEAR) },
      { id: "4-series", name: "4 Series", years: range(2014, CURRENT_YEAR) },
      { id: "5-series", name: "5 Series", years: range(1990, CURRENT_YEAR) },
      { id: "7-series", name: "7 Series", years: range(1995, CURRENT_YEAR) },
      { id: "8-series", name: "8 Series", years: range(2019, CURRENT_YEAR) },
      { id: "x1", name: "X1", years: range(2013, CURRENT_YEAR) },
      { id: "x2", name: "X2", years: range(2018, CURRENT_YEAR) },
      { id: "x3", name: "X3", years: range(2004, CURRENT_YEAR) },
      { id: "x4", name: "X4", years: range(2015, CURRENT_YEAR) },
      { id: "x5", name: "X5", years: range(2000, CURRENT_YEAR) },
      { id: "x6", name: "X6", years: range(2008, CURRENT_YEAR) },
      { id: "x7", name: "X7", years: range(2019, CURRENT_YEAR) },
      { id: "xm", name: "XM", years: range(2023, CURRENT_YEAR) },
      { id: "z4", name: "Z4", years: range(2003, CURRENT_YEAR) },
      { id: "i4", name: "i4", years: range(2022, CURRENT_YEAR) },
      { id: "i5", name: "i5", years: range(2024, CURRENT_YEAR) },
      { id: "i7", name: "i7", years: range(2023, CURRENT_YEAR) },
      { id: "ix", name: "iX", years: range(2022, CURRENT_YEAR) },
      { id: "m3", name: "M3", years: range(1995, CURRENT_YEAR) },
      { id: "m4", name: "M4", years: range(2015, CURRENT_YEAR) },
      { id: "m5", name: "M5", years: range(1998, CURRENT_YEAR) },
    ],
  },
  {
    id: "buick",
    name: "Buick",
    models: [
      { id: "enclave", name: "Enclave", years: range(2008, CURRENT_YEAR) },
      { id: "encore", name: "Encore", years: range(2013, CURRENT_YEAR) },
      { id: "encore-gx", name: "Encore GX", years: range(2020, CURRENT_YEAR) },
      { id: "envista", name: "Envista", years: range(2024, CURRENT_YEAR) },
      { id: "envision", name: "Envision", years: range(2016, CURRENT_YEAR) },
      { id: "lacrosse", name: "LaCrosse", years: range(2005, 2019) },
      { id: "regal", name: "Regal", years: range(2011, 2020) },
    ],
  },
  {
    id: "cadillac",
    name: "Cadillac",
    models: [
      { id: "ct4", name: "CT4", years: range(2020, CURRENT_YEAR) },
      { id: "ct5", name: "CT5", years: range(2020, CURRENT_YEAR) },
      { id: "escalade", name: "Escalade", years: range(1999, CURRENT_YEAR) },
      { id: "xt4", name: "XT4", years: range(2019, CURRENT_YEAR) },
      { id: "xt5", name: "XT5", years: range(2017, CURRENT_YEAR) },
      { id: "xt6", name: "XT6", years: range(2020, CURRENT_YEAR) },
      { id: "lyriq", name: "LYRIQ", years: range(2023, CURRENT_YEAR) },
      { id: "cts", name: "CTS", years: range(2003, 2019) },
      { id: "srx", name: "SRX", years: range(2004, 2016) },
    ],
  },
  {
    id: "chevrolet",
    name: "Chevrolet",
    models: [
      { id: "blazer", name: "Blazer", years: range(2019, CURRENT_YEAR) },
      { id: "bolt-ev", name: "Bolt EV", years: range(2017, 2023) },
      { id: "bolt-euv", name: "Bolt EUV", years: range(2022, 2023) },
      { id: "camaro", name: "Camaro", years: range(2010, 2024) },
      { id: "colorado", name: "Colorado", years: range(2004, CURRENT_YEAR) },
      { id: "corvette", name: "Corvette", years: range(1997, CURRENT_YEAR) },
      { id: "cruze", name: "Cruze", years: range(2011, 2019) },
      { id: "equinox", name: "Equinox", years: range(2005, CURRENT_YEAR) },
      { id: "express", name: "Express", years: range(1996, CURRENT_YEAR) },
      { id: "impala", name: "Impala", years: range(2000, 2020) },
      { id: "malibu", name: "Malibu", years: range(1997, 2024) },
      { id: "silverado-1500", name: "Silverado 1500", years: range(1999, CURRENT_YEAR) },
      { id: "silverado-2500hd", name: "Silverado 2500HD", years: range(2001, CURRENT_YEAR) },
      { id: "silverado-3500hd", name: "Silverado 3500HD", years: range(2001, CURRENT_YEAR) },
      { id: "silverado-ev", name: "Silverado EV", years: range(2024, CURRENT_YEAR) },
      { id: "spark", name: "Spark", years: range(2013, 2022) },
      { id: "suburban", name: "Suburban", years: range(1992, CURRENT_YEAR) },
      { id: "tahoe", name: "Tahoe", years: range(1995, CURRENT_YEAR) },
      { id: "trailblazer", name: "Trailblazer", years: range(2021, CURRENT_YEAR) },
      { id: "traverse", name: "Traverse", years: range(2009, CURRENT_YEAR) },
      { id: "trax", name: "Trax", years: range(2015, CURRENT_YEAR) },
    ],
  },
  {
    id: "chrysler",
    name: "Chrysler",
    models: [
      { id: "300", name: "300", years: range(2005, 2023) },
      { id: "pacifica", name: "Pacifica", years: range(2017, CURRENT_YEAR) },
      { id: "voyager", name: "Voyager", years: range(2020, 2022) },
    ],
  },
  {
    id: "dodge",
    name: "Dodge",
    models: [
      { id: "challenger", name: "Challenger", years: range(2008, 2023) },
      { id: "charger", name: "Charger", years: range(2006, CURRENT_YEAR) },
      { id: "durango", name: "Durango", years: range(1998, CURRENT_YEAR) },
      { id: "grand-caravan", name: "Grand Caravan", years: range(1996, 2020) },
      { id: "hornet", name: "Hornet", years: range(2023, CURRENT_YEAR) },
      { id: "journey", name: "Journey", years: range(2009, 2020) },
    ],
  },
  {
    id: "fiat",
    name: "FIAT",
    models: [
      { id: "500", name: "500", years: range(2012, 2019) },
      { id: "500x", name: "500X", years: range(2016, 2023) },
      { id: "500e", name: "500e", years: range(2024, CURRENT_YEAR) },
    ],
  },
  {
    id: "ford",
    name: "Ford",
    models: [
      { id: "bronco", name: "Bronco", years: range(2021, CURRENT_YEAR) },
      { id: "bronco-sport", name: "Bronco Sport", years: range(2021, CURRENT_YEAR) },
      { id: "edge", name: "Edge", years: range(2007, 2024) },
      { id: "escape", name: "Escape", years: range(2001, CURRENT_YEAR) },
      { id: "expedition", name: "Expedition", years: range(1997, CURRENT_YEAR) },
      { id: "explorer", name: "Explorer", years: range(1991, CURRENT_YEAR) },
      { id: "f-150", name: "F-150", years: range(1992, CURRENT_YEAR) },
      { id: "f-150-lightning", name: "F-150 Lightning", years: range(2022, CURRENT_YEAR) },
      { id: "f-250", name: "F-250", years: range(1999, CURRENT_YEAR) },
      { id: "f-350", name: "F-350", years: range(1999, CURRENT_YEAR) },
      { id: "fiesta", name: "Fiesta", years: range(2011, 2019) },
      { id: "flex", name: "Flex", years: range(2009, 2019) },
      { id: "focus", name: "Focus", years: range(2000, 2018) },
      { id: "fusion", name: "Fusion", years: range(2006, 2020) },
      { id: "maverick", name: "Maverick", years: range(2022, CURRENT_YEAR) },
      { id: "mustang", name: "Mustang", years: range(1994, CURRENT_YEAR) },
      { id: "mustang-mach-e", name: "Mustang Mach-E", years: range(2021, CURRENT_YEAR) },
      { id: "ranger", name: "Ranger", years: range(1993, CURRENT_YEAR) },
      { id: "transit", name: "Transit", years: range(2015, CURRENT_YEAR) },
      { id: "transit-connect", name: "Transit Connect", years: range(2010, 2023) },
    ],
  },
  {
    id: "genesis",
    name: "Genesis",
    models: [
      { id: "g70", name: "G70", years: range(2019, CURRENT_YEAR) },
      { id: "g80", name: "G80", years: range(2017, CURRENT_YEAR) },
      { id: "g90", name: "G90", years: range(2017, CURRENT_YEAR) },
      { id: "gv60", name: "GV60", years: range(2023, CURRENT_YEAR) },
      { id: "gv70", name: "GV70", years: range(2022, CURRENT_YEAR) },
      { id: "gv80", name: "GV80", years: range(2021, CURRENT_YEAR) },
    ],
  },
  {
    id: "gmc",
    name: "GMC",
    models: [
      { id: "acadia", name: "Acadia", years: range(2007, CURRENT_YEAR) },
      { id: "canyon", name: "Canyon", years: range(2004, CURRENT_YEAR) },
      { id: "hummer-ev", name: "HUMMER EV", years: range(2022, CURRENT_YEAR) },
      { id: "savana", name: "Savana", years: range(1996, CURRENT_YEAR) },
      { id: "sierra-1500", name: "Sierra 1500", years: range(1999, CURRENT_YEAR) },
      { id: "sierra-2500hd", name: "Sierra 2500HD", years: range(2001, CURRENT_YEAR) },
      { id: "sierra-3500hd", name: "Sierra 3500HD", years: range(2001, CURRENT_YEAR) },
      { id: "terrain", name: "Terrain", years: range(2010, CURRENT_YEAR) },
      { id: "yukon", name: "Yukon", years: range(1992, CURRENT_YEAR) },
      { id: "yukon-xl", name: "Yukon XL", years: range(2000, CURRENT_YEAR) },
    ],
  },
  {
    id: "honda",
    name: "Honda",
    models: [
      { id: "accord", name: "Accord", years: range(1990, CURRENT_YEAR) },
      { id: "civic", name: "Civic", years: range(1990, CURRENT_YEAR) },
      { id: "cr-v", name: "CR-V", years: range(1997, CURRENT_YEAR) },
      { id: "element", name: "Element", years: range(2003, 2011) },
      { id: "fit", name: "Fit", years: range(2007, 2020) },
      { id: "hr-v", name: "HR-V", years: range(2016, CURRENT_YEAR) },
      { id: "insight", name: "Insight", years: range(2019, 2022) },
      { id: "odyssey", name: "Odyssey", years: range(1995, CURRENT_YEAR) },
      { id: "passport", name: "Passport", years: range(2019, CURRENT_YEAR) },
      { id: "pilot", name: "Pilot", years: range(2003, CURRENT_YEAR) },
      { id: "prologue", name: "Prologue", years: range(2024, CURRENT_YEAR) },
      { id: "ridgeline", name: "Ridgeline", years: range(2006, CURRENT_YEAR) },
    ],
  },
  {
    id: "hyundai",
    name: "Hyundai",
    models: [
      { id: "accent", name: "Accent", years: range(2000, 2022) },
      { id: "elantra", name: "Elantra", years: range(1996, CURRENT_YEAR) },
      { id: "ioniq-5", name: "IONIQ 5", years: range(2022, CURRENT_YEAR) },
      { id: "ioniq-6", name: "IONIQ 6", years: range(2023, CURRENT_YEAR) },
      { id: "kona", name: "Kona", years: range(2018, CURRENT_YEAR) },
      { id: "palisade", name: "Palisade", years: range(2020, CURRENT_YEAR) },
      { id: "santa-cruz", name: "Santa Cruz", years: range(2022, CURRENT_YEAR) },
      { id: "santa-fe", name: "Santa Fe", years: range(2001, CURRENT_YEAR) },
      { id: "sonata", name: "Sonata", years: range(1999, CURRENT_YEAR) },
      { id: "tucson", name: "Tucson", years: range(2005, CURRENT_YEAR) },
      { id: "venue", name: "Venue", years: range(2020, CURRENT_YEAR) },
      { id: "veloster", name: "Veloster", years: range(2012, 2021) },
    ],
  },
  {
    id: "infiniti",
    name: "INFINITI",
    models: [
      { id: "q50", name: "Q50", years: range(2014, CURRENT_YEAR) },
      { id: "q60", name: "Q60", years: range(2017, 2022) },
      { id: "qx50", name: "QX50", years: range(2014, CURRENT_YEAR) },
      { id: "qx55", name: "QX55", years: range(2022, CURRENT_YEAR) },
      { id: "qx60", name: "QX60", years: range(2013, CURRENT_YEAR) },
      { id: "qx80", name: "QX80", years: range(2011, CURRENT_YEAR) },
      { id: "g37", name: "G37", years: range(2008, 2013) },
    ],
  },
  {
    id: "jaguar",
    name: "Jaguar",
    models: [
      { id: "e-pace", name: "E-PACE", years: range(2018, 2024) },
      { id: "f-pace", name: "F-PACE", years: range(2017, CURRENT_YEAR) },
      { id: "f-type", name: "F-TYPE", years: range(2014, 2024) },
      { id: "xe", name: "XE", years: range(2017, 2020) },
      { id: "xf", name: "XF", years: range(2009, 2024) },
      { id: "i-pace", name: "I-PACE", years: range(2019, 2024) },
    ],
  },
  {
    id: "jeep",
    name: "Jeep",
    models: [
      { id: "cherokee", name: "Cherokee", years: range(2014, 2023) },
      { id: "compass", name: "Compass", years: range(2007, CURRENT_YEAR) },
      { id: "gladiator", name: "Gladiator", years: range(2020, CURRENT_YEAR) },
      { id: "grand-cherokee", name: "Grand Cherokee", years: range(1999, CURRENT_YEAR) },
      { id: "grand-cherokee-l", name: "Grand Cherokee L", years: range(2021, CURRENT_YEAR) },
      { id: "grand-wagoneer", name: "Grand Wagoneer", years: range(2022, CURRENT_YEAR) },
      { id: "renegade", name: "Renegade", years: range(2015, CURRENT_YEAR) },
      { id: "wagoneer", name: "Wagoneer", years: range(2022, CURRENT_YEAR) },
      { id: "wrangler", name: "Wrangler", years: range(1997, CURRENT_YEAR) },
    ],
  },
  {
    id: "kia",
    name: "Kia",
    models: [
      { id: "carnival", name: "Carnival", years: range(2022, CURRENT_YEAR) },
      { id: "ev6", name: "EV6", years: range(2022, CURRENT_YEAR) },
      { id: "ev9", name: "EV9", years: range(2024, CURRENT_YEAR) },
      { id: "forte", name: "Forte", years: range(2010, CURRENT_YEAR) },
      { id: "k5", name: "K5", years: range(2021, CURRENT_YEAR) },
      { id: "niro", name: "Niro", years: range(2017, CURRENT_YEAR) },
      { id: "optima", name: "Optima", years: range(2001, 2020) },
      { id: "rio", name: "Rio", years: range(2001, 2023) },
      { id: "seltos", name: "Seltos", years: range(2021, CURRENT_YEAR) },
      { id: "sorento", name: "Sorento", years: range(2003, CURRENT_YEAR) },
      { id: "soul", name: "Soul", years: range(2010, CURRENT_YEAR) },
      { id: "sportage", name: "Sportage", years: range(2005, CURRENT_YEAR) },
      { id: "stinger", name: "Stinger", years: range(2018, 2023) },
      { id: "telluride", name: "Telluride", years: range(2020, CURRENT_YEAR) },
    ],
  },
  {
    id: "land-rover",
    name: "Land Rover",
    models: [
      { id: "defender", name: "Defender", years: range(2020, CURRENT_YEAR) },
      { id: "discovery", name: "Discovery", years: range(2017, CURRENT_YEAR) },
      { id: "discovery-sport", name: "Discovery Sport", years: range(2015, CURRENT_YEAR) },
      { id: "range-rover", name: "Range Rover", years: range(2003, CURRENT_YEAR) },
      { id: "range-rover-evoque", name: "Range Rover Evoque", years: range(2012, CURRENT_YEAR) },
      { id: "range-rover-sport", name: "Range Rover Sport", years: range(2006, CURRENT_YEAR) },
      { id: "range-rover-velar", name: "Range Rover Velar", years: range(2018, CURRENT_YEAR) },
    ],
  },
  {
    id: "lexus",
    name: "Lexus",
    models: [
      { id: "es", name: "ES", years: range(1997, CURRENT_YEAR) },
      { id: "gx", name: "GX", years: range(2003, CURRENT_YEAR) },
      { id: "is", name: "IS", years: range(2001, CURRENT_YEAR) },
      { id: "lx", name: "LX", years: range(1996, CURRENT_YEAR) },
      { id: "nx", name: "NX", years: range(2015, CURRENT_YEAR) },
      { id: "rc", name: "RC", years: range(2015, CURRENT_YEAR) },
      { id: "rx", name: "RX", years: range(1999, CURRENT_YEAR) },
      { id: "rz", name: "RZ", years: range(2023, CURRENT_YEAR) },
      { id: "tx", name: "TX", years: range(2024, CURRENT_YEAR) },
      { id: "ux", name: "UX", years: range(2019, CURRENT_YEAR) },
      { id: "lc", name: "LC", years: range(2018, CURRENT_YEAR) },
    ],
  },
  {
    id: "lincoln",
    name: "Lincoln",
    models: [
      { id: "aviator", name: "Aviator", years: range(2020, CURRENT_YEAR) },
      { id: "corsair", name: "Corsair", years: range(2020, CURRENT_YEAR) },
      { id: "nautilus", name: "Nautilus", years: range(2019, CURRENT_YEAR) },
      { id: "navigator", name: "Navigator", years: range(1998, CURRENT_YEAR) },
      { id: "mkz", name: "MKZ", years: range(2006, 2020) },
      { id: "mkc", name: "MKC", years: range(2015, 2019) },
      { id: "mkx", name: "MKX", years: range(2007, 2018) },
    ],
  },
  {
    id: "maserati",
    name: "Maserati",
    models: [
      { id: "ghibli", name: "Ghibli", years: range(2014, 2023) },
      { id: "granturismo", name: "GranTurismo", years: range(2008, CURRENT_YEAR) },
      { id: "grecale", name: "Grecale", years: range(2023, CURRENT_YEAR) },
      { id: "levante", name: "Levante", years: range(2017, CURRENT_YEAR) },
      { id: "quattroporte", name: "Quattroporte", years: range(2005, 2023) },
    ],
  },
  {
    id: "mazda",
    name: "Mazda",
    models: [
      { id: "cx-30", name: "CX-30", years: range(2020, CURRENT_YEAR) },
      { id: "cx-5", name: "CX-5", years: range(2013, CURRENT_YEAR) },
      { id: "cx-50", name: "CX-50", years: range(2023, CURRENT_YEAR) },
      { id: "cx-70", name: "CX-70", years: range(2025, CURRENT_YEAR) },
      { id: "cx-9", name: "CX-9", years: range(2007, 2023) },
      { id: "cx-90", name: "CX-90", years: range(2024, CURRENT_YEAR) },
      { id: "mazda3", name: "Mazda3", years: range(2004, CURRENT_YEAR) },
      { id: "mazda6", name: "Mazda6", years: range(2003, 2021) },
      { id: "mx-5-miata", name: "MX-5 Miata", years: range(1990, CURRENT_YEAR) },
    ],
  },
  {
    id: "mercedes-benz",
    name: "Mercedes-Benz",
    models: [
      { id: "a-class", name: "A-Class", years: range(2019, 2022) },
      { id: "c-class", name: "C-Class", years: range(1994, CURRENT_YEAR) },
      { id: "cla", name: "CLA", years: range(2014, CURRENT_YEAR) },
      { id: "cls", name: "CLS", years: range(2006, 2024) },
      { id: "e-class", name: "E-Class", years: range(1996, CURRENT_YEAR) },
      { id: "eqb", name: "EQB", years: range(2022, CURRENT_YEAR) },
      { id: "eqe", name: "EQE", years: range(2023, CURRENT_YEAR) },
      { id: "eqs", name: "EQS", years: range(2022, CURRENT_YEAR) },
      { id: "g-class", name: "G-Class", years: range(2002, CURRENT_YEAR) },
      { id: "gla", name: "GLA", years: range(2015, CURRENT_YEAR) },
      { id: "glb", name: "GLB", years: range(2020, CURRENT_YEAR) },
      { id: "glc", name: "GLC", years: range(2016, CURRENT_YEAR) },
      { id: "gle", name: "GLE", years: range(2016, CURRENT_YEAR) },
      { id: "gls", name: "GLS", years: range(2017, CURRENT_YEAR) },
      { id: "s-class", name: "S-Class", years: range(2000, CURRENT_YEAR) },
      { id: "sl", name: "SL", years: range(2003, CURRENT_YEAR) },
      { id: "amg-gt", name: "AMG GT", years: range(2016, CURRENT_YEAR) },
    ],
  },
  {
    id: "mini",
    name: "MINI",
    models: [
      { id: "cooper", name: "Cooper", years: range(2002, CURRENT_YEAR) },
      { id: "countryman", name: "Countryman", years: range(2011, CURRENT_YEAR) },
      { id: "clubman", name: "Clubman", years: range(2008, 2024) },
    ],
  },
  {
    id: "mitsubishi",
    name: "Mitsubishi",
    models: [
      { id: "eclipse-cross", name: "Eclipse Cross", years: range(2018, CURRENT_YEAR) },
      { id: "mirage", name: "Mirage", years: range(2014, CURRENT_YEAR) },
      { id: "outlander", name: "Outlander", years: range(2007, CURRENT_YEAR) },
      { id: "outlander-sport", name: "Outlander Sport", years: range(2011, CURRENT_YEAR) },
    ],
  },
  {
    id: "nissan",
    name: "Nissan",
    models: [
      { id: "altima", name: "Altima", years: range(1998, CURRENT_YEAR) },
      { id: "ariya", name: "Ariya", years: range(2023, CURRENT_YEAR) },
      { id: "armada", name: "Armada", years: range(2004, CURRENT_YEAR) },
      { id: "frontier", name: "Frontier", years: range(1998, CURRENT_YEAR) },
      { id: "kicks", name: "Kicks", years: range(2018, CURRENT_YEAR) },
      { id: "leaf", name: "LEAF", years: range(2011, 2024) },
      { id: "maxima", name: "Maxima", years: range(1995, 2023) },
      { id: "murano", name: "Murano", years: range(2003, CURRENT_YEAR) },
      { id: "pathfinder", name: "Pathfinder", years: range(1996, CURRENT_YEAR) },
      { id: "rogue", name: "Rogue", years: range(2008, CURRENT_YEAR) },
      { id: "rogue-sport", name: "Rogue Sport", years: range(2017, 2022) },
      { id: "sentra", name: "Sentra", years: range(2000, CURRENT_YEAR) },
      { id: "titan", name: "Titan", years: range(2004, CURRENT_YEAR) },
      { id: "versa", name: "Versa", years: range(2007, CURRENT_YEAR) },
      { id: "z", name: "Z", years: range(2023, CURRENT_YEAR) },
      { id: "370z", name: "370Z", years: range(2009, 2020) },
    ],
  },
  {
    id: "porsche",
    name: "Porsche",
    models: [
      { id: "718-boxster", name: "718 Boxster", years: range(2017, CURRENT_YEAR) },
      { id: "718-cayman", name: "718 Cayman", years: range(2017, CURRENT_YEAR) },
      { id: "911", name: "911", years: range(1999, CURRENT_YEAR) },
      { id: "cayenne", name: "Cayenne", years: range(2003, CURRENT_YEAR) },
      { id: "macan", name: "Macan", years: range(2015, CURRENT_YEAR) },
      { id: "panamera", name: "Panamera", years: range(2010, CURRENT_YEAR) },
      { id: "taycan", name: "Taycan", years: range(2020, CURRENT_YEAR) },
    ],
  },
  {
    id: "ram",
    name: "RAM",
    models: [
      { id: "1500", name: "1500", years: range(2011, CURRENT_YEAR) },
      { id: "2500", name: "2500", years: range(2011, CURRENT_YEAR) },
      { id: "3500", name: "3500", years: range(2011, CURRENT_YEAR) },
      { id: "promaster", name: "ProMaster", years: range(2014, CURRENT_YEAR) },
      { id: "promaster-city", name: "ProMaster City", years: range(2015, 2022) },
    ],
  },
  {
    id: "rivian",
    name: "Rivian",
    models: [
      { id: "r1s", name: "R1S", years: range(2022, CURRENT_YEAR) },
      { id: "r1t", name: "R1T", years: range(2022, CURRENT_YEAR) },
    ],
  },
  {
    id: "subaru",
    name: "Subaru",
    models: [
      { id: "brz", name: "BRZ", years: range(2013, CURRENT_YEAR) },
      { id: "crosstrek", name: "Crosstrek", years: range(2013, CURRENT_YEAR) },
      { id: "forester", name: "Forester", years: range(1998, CURRENT_YEAR) },
      { id: "impreza", name: "Impreza", years: range(1993, CURRENT_YEAR) },
      { id: "legacy", name: "Legacy", years: range(1995, CURRENT_YEAR) },
      { id: "outback", name: "Outback", years: range(2000, CURRENT_YEAR) },
      { id: "solterra", name: "Solterra", years: range(2023, CURRENT_YEAR) },
      { id: "wrx", name: "WRX", years: range(2002, CURRENT_YEAR) },
      { id: "ascent", name: "Ascent", years: range(2019, CURRENT_YEAR) },
    ],
  },
  {
    id: "tesla",
    name: "Tesla",
    models: [
      { id: "model-3", name: "Model 3", years: range(2017, CURRENT_YEAR) },
      { id: "model-s", name: "Model S", years: range(2012, CURRENT_YEAR) },
      { id: "model-x", name: "Model X", years: range(2016, CURRENT_YEAR) },
      { id: "model-y", name: "Model Y", years: range(2020, CURRENT_YEAR) },
      { id: "cybertruck", name: "Cybertruck", years: range(2024, CURRENT_YEAR) },
    ],
  },
  {
    id: "toyota",
    name: "Toyota",
    models: [
      { id: "4runner", name: "4Runner", years: range(1996, CURRENT_YEAR) },
      { id: "86", name: "GR86", years: range(2022, CURRENT_YEAR) },
      { id: "avalon", name: "Avalon", years: range(1995, 2022) },
      { id: "bz4x", name: "bZ4X", years: range(2023, CURRENT_YEAR) },
      { id: "camry", name: "Camry", years: range(1992, CURRENT_YEAR) },
      { id: "corolla", name: "Corolla", years: range(1990, CURRENT_YEAR) },
      { id: "corolla-cross", name: "Corolla Cross", years: range(2022, CURRENT_YEAR) },
      { id: "crown", name: "Crown", years: range(2023, CURRENT_YEAR) },
      { id: "grand-highlander", name: "Grand Highlander", years: range(2024, CURRENT_YEAR) },
      { id: "gr-corolla", name: "GR Corolla", years: range(2023, CURRENT_YEAR) },
      { id: "gr-supra", name: "GR Supra", years: range(2020, CURRENT_YEAR) },
      { id: "highlander", name: "Highlander", years: range(2001, CURRENT_YEAR) },
      { id: "land-cruiser", name: "Land Cruiser", years: range(1998, CURRENT_YEAR) },
      { id: "prius", name: "Prius", years: range(2001, CURRENT_YEAR) },
      { id: "rav4", name: "RAV4", years: range(1996, CURRENT_YEAR) },
      { id: "sequoia", name: "Sequoia", years: range(2001, CURRENT_YEAR) },
      { id: "sienna", name: "Sienna", years: range(1998, CURRENT_YEAR) },
      { id: "tacoma", name: "Tacoma", years: range(1995, CURRENT_YEAR) },
      { id: "tundra", name: "Tundra", years: range(2000, CURRENT_YEAR) },
      { id: "venza", name: "Venza", years: range(2021, CURRENT_YEAR) },
      { id: "yaris", name: "Yaris", years: range(2007, 2020) },
    ],
  },
  {
    id: "volkswagen",
    name: "Volkswagen",
    models: [
      { id: "atlas", name: "Atlas", years: range(2018, CURRENT_YEAR) },
      { id: "atlas-cross-sport", name: "Atlas Cross Sport", years: range(2020, CURRENT_YEAR) },
      { id: "golf", name: "Golf", years: range(1999, CURRENT_YEAR) },
      { id: "golf-gti", name: "Golf GTI", years: range(2006, CURRENT_YEAR) },
      { id: "golf-r", name: "Golf R", years: range(2012, CURRENT_YEAR) },
      { id: "id4", name: "ID.4", years: range(2021, CURRENT_YEAR) },
      { id: "id-buzz", name: "ID. Buzz", years: range(2024, CURRENT_YEAR) },
      { id: "jetta", name: "Jetta", years: range(1999, CURRENT_YEAR) },
      { id: "jetta-gli", name: "Jetta GLI", years: range(2006, CURRENT_YEAR) },
      { id: "passat", name: "Passat", years: range(1998, 2022) },
      { id: "taos", name: "Taos", years: range(2022, CURRENT_YEAR) },
      { id: "tiguan", name: "Tiguan", years: range(2009, CURRENT_YEAR) },
    ],
  },
  {
    id: "volvo",
    name: "Volvo",
    models: [
      { id: "c40-recharge", name: "C40 Recharge", years: range(2022, CURRENT_YEAR) },
      { id: "ex30", name: "EX30", years: range(2024, CURRENT_YEAR) },
      { id: "ex90", name: "EX90", years: range(2024, CURRENT_YEAR) },
      { id: "s60", name: "S60", years: range(2001, CURRENT_YEAR) },
      { id: "s90", name: "S90", years: range(2017, CURRENT_YEAR) },
      { id: "v60", name: "V60", years: range(2019, CURRENT_YEAR) },
      { id: "v90", name: "V90", years: range(2017, 2024) },
      { id: "xc40", name: "XC40", years: range(2019, CURRENT_YEAR) },
      { id: "xc40-recharge", name: "XC40 Recharge", years: range(2021, CURRENT_YEAR) },
      { id: "xc60", name: "XC60", years: range(2010, CURRENT_YEAR) },
      { id: "xc90", name: "XC90", years: range(2003, CURRENT_YEAR) },
    ],
  },
  {
    id: "lucid",
    name: "Lucid",
    models: [
      { id: "air", name: "Air", years: range(2022, CURRENT_YEAR) },
      { id: "gravity", name: "Gravity", years: range(2025, CURRENT_YEAR) },
    ],
  },
  {
    id: "polestar",
    name: "Polestar",
    models: [
      { id: "polestar-2", name: "Polestar 2", years: range(2020, CURRENT_YEAR) },
      { id: "polestar-3", name: "Polestar 3", years: range(2024, CURRENT_YEAR) },
    ],
  },
];

export function getVehicleImagePath(brandId, modelId, year) {
  const slug = `${brandId}${modelId}${year}`.replace(/-/g, "");
  return `/vehicles/${slug}.png`;
}
